### ISSUE TITLE
MacOS M2 Max - Cannot run

### ISSUE THREAD

**Issue by dangarfield** [UrielCh/opencv4nodejs#104]
Details:
- MacOS - Ventura 13.4.1 (22F82)
- Processor - Apple M2 Max
- Nodejs - v20.3.1
- npm - 9.7.2

Error:
- `npm i @u4/opencv4nodejs` - Successful install, no issues
- `brew install opencv` - Success.
- Added package.json config: ```"opencv4nodejs": {
    "disableAutoBuild": 1,
    "opencvIncludeDir": "/opt/homebrew/Cellar/opencv/4.8.0/include/opencv4",
    "opencvLibDir": "/opt/homebrew/Cellar/opencv/4.8.0/lib",
    "opencvBinDir": "/opt/homebrew/Cellar/opencv/4.8.0/bin",
    "opencvDir": "/opt/homebrew/Cellar/opencv/4.8.0"
  }```
- When running a node app, using const cv = require('@u4/opencv4nodejs') -> error:

```
xx@xx eve-dg-miner % node app.js
info config found opencv4nodejs section in /Users/xx/code/eve-dg-miner/package.json
info applyEnvsFromPackageJson the following opencv4nodejs environment variables are set in the package.json:
info applyEnvsFromPackageJson disableAutoBuild: 1
info applyEnvsFromPackageJson opencvIncludeDir: /opt/homebrew/Cellar/opencv/4.8.0/include/opencv4
info applyEnvsFromPackageJson opencvLibDir: /opt/homebrew/Cellar/opencv/4.8.0/lib
info applyEnvsFromPackageJson opencvBinDir: /opt/homebrew/Cellar/opencv/4.8.0/bin
info applyEnvsFromPackageJson opencvDir: /opt/homebrew/Cellar/opencv/4.8.0
/Users/xx/code/eve-dg-miner/node_modules/@u4/opencv4nodejs/lib/cvloader.js:62
            throw err;
            ^

Error: Cannot find module '/Users/xx/code/eve-dg-miner/node_modules/@u4/opencv4nodejs/build/Release/opencv4nodejs'
Require stack:
- /Users/xx/code/eve-dg-miner/node_modules/@u4/opencv4nodejs/lib/cvloader.js
- /Users/xx/code/eve-dg-miner/node_modules/@u4/opencv4nodejs/lib/opencv4nodejs.js
- /Users/xx/code/eve-dg-miner/app.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1072:15)
    at Module._load (node:internal/modules/cjs/loader:925:27)
    at Module.require (node:internal/modules/cjs/loader:1139:19)
    at require (node:internal/modules/helpers:121:18)
    at getOpenCV (/Users/xx/code/eve-dg-miner/node_modules/@u4/opencv4nodejs/lib/cvloader.js:54:23)
    at loadOpenCV (/Users/xx/code/eve-dg-miner/node_modules/@u4/opencv4nodejs/lib/opencv4nodejs.js:6:48)
    at Object.<anonymous> (/Users/x/code/eve-dg-miner/node_modules/@u4/opencv4nodejs/lib/opencv4nodejs.js:21:12)
    at Module._compile (node:internal/modules/cjs/loader:1257:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1311:10)
    at Module.load (node:internal/modules/cjs/loader:1115:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/xx/code/eve-dg-miner/node_modules/@u4/opencv4nodejs/lib/cvloader.js',
    '/Users/xx/code/eve-dg-miner/node_modules/@u4/opencv4nodejs/lib/opencv4nodejs.js',
    '/Users/xx/code/eve-dg-miner/app.js'
  ]
}
```

I'm struggling to get opencv4nodejs installed properly, and I see that you've done a great job of prebuilding. Should my system work or is this to be expected at this point?
Thanks

**Comment by UrielCh** [comment]
you should try a tested version, I did not tryed yet V4.8.0.

**Comment by maxrostron** [comment]
@dangarfield - did you manage to overcome this?
@UrielCh - does v4.8.0 work yet?

**Comment by podoliachenko** [comment]
I have the same problem with m2.
I can not install 4.6, but 4.8 does not work

**Comment by chenrenxing** [comment]
I also have the same problem with the M1 chip I am using

**Comment by petem24** [comment]
Same issue here. M1

**Comment by mkkurt** [comment]
same

**Comment by hwang1607** [comment]
i have the same issue on mac but on intel
