### ISSUE TITLE
node-gyp error when building

### ISSUE THREAD

**Issue by BleedFeed** [UrielCh/opencv4nodejs#105]
hi,

i get an error when i try to run `$ build-opencv --version 4.6.0 --buildRoot ~/openCV build`

```
info install Spawning in directory:/home/eren/Downloads/opencv/node_modules/@u4/opencv4nodejs node-gyp process: node-gyp build --jobs max --release 
gyp info it worked if it ends with ok
gyp info using node-gyp@9.4.0
gyp info using node@20.3.1 | linux | x64

gyp ERR! build error 
gyp ERR! stack Error: You must run `node-gyp configure` first!
gyp ERR! stack     at ReadFileContext.<anonymous> (/usr/lib/node_modules/node-gyp/lib/build.js:45:20)
gyp ERR! stack     at ReadFileContext.callback (/usr/lib/node_modules/node-gyp/node_modules/graceful-fs/graceful-fs.js:123:16)
gyp ERR! stack     at FSReqCallback.readFileAfterOpen [as oncomplete] (node:fs:315:13)
gyp ERR! System Linux 5.19.0-46-generic
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "build" "--jobs" "max" "--release"
gyp ERR! cwd /home/eren/Downloads/opencv/node_modules/@u4/opencv4nodejs
gyp ERR! node -v v20.3.1
gyp ERR! node-gyp -v v9.4.0
gyp ERR! not ok 
error:  Error: Command failed: node-gyp build --jobs max --release 
gyp info it worked if it ends with ok
gyp info using node-gyp@9.4.0
gyp info using node@20.3.1 | linux | x64
gyp ERR! build error 
gyp ERR! stack Error: You must run `node-gyp configure` first!
gyp ERR! stack     at ReadFileContext.<anonymous> (/usr/lib/node_modules/node-gyp/lib/build.js:45:20)
gyp ERR! stack     at ReadFileContext.callback (/usr/lib/node_modules/node-gyp/node_modules/graceful-fs/graceful-fs.js:123:16)
gyp ERR! stack     at FSReqCallback.readFileAfterOpen [as oncomplete] (node:fs:315:13)
gyp ERR! System Linux 5.19.0-46-generic
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "build" "--jobs" "max" "--release"
gyp ERR! cwd /home/eren/Downloads/opencv/node_modules/@u4/opencv4nodejs
gyp ERR! node -v v20.3.1
gyp ERR! node-gyp -v v9.4.0
gyp ERR! not ok 

    at ChildProcess.exithandler (node:child_process:419:12)
    at ChildProcess.emit (node:events:511:28)
    at maybeClose (node:internal/child_process:1098:16)
    at ChildProcess._handle.onexit (node:internal/child_process:304:5) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'node-gyp build --jobs max --release '
}
ERR! install node-gyp failed and return Error Command failed: node-gyp build --jobs max --release 
ERR! install gyp info it worked if it ends with ok
ERR! install gyp info using node-gyp@9.4.0
ERR! install gyp info using node@20.3.1 | linux | x64
ERR! install gyp ERR! build error 
ERR! install gyp ERR! stack Error: You must run `node-gyp configure` first!
ERR! install gyp ERR! stack     at ReadFileContext.<anonymous> (/usr/lib/node_modules/node-gyp/lib/build.js:45:20)
ERR! install gyp ERR! stack     at ReadFileContext.callback (/usr/lib/node_modules/node-gyp/node_modules/graceful-fs/graceful-fs.js:123:16)
ERR! install gyp ERR! stack     at FSReqCallback.readFileAfterOpen [as oncomplete] (node:fs:315:13)
ERR! install gyp ERR! System Linux 5.19.0-46-generic
ERR! install gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "build" "--jobs" "max" "--release"
ERR! install gyp ERR! cwd /home/eren/Downloads/opencv/node_modules/@u4/opencv4nodejs
ERR! install gyp ERR! node -v v20.3.1
ERR! install gyp ERR! node-gyp -v v9.4.0
ERR! install gyp ERR! not ok 
ERR! install  return code: 1
```

**Comment by BleedFeed** [comment]
found solution in FAQ #20
