### ISSUE TITLE
An error occurred when I executed the npx build-opencv --version 4.6.0 rebuild command

### ISSUE THREAD

**Issue by jay-gaojing** [UrielCh/opencv4nodejs#136]
![image](https://github.com/UrielCh/opencv4nodejs/assets/64359368/07aba6a7-bc16-46dd-a568-8dd55cb9ca4a)

**Comment by UrielCh** [comment]
@u4/Opencv-build@1.0.0 is not compatible with V6.

please upgrade to @u4/opencv4nodejs@V7

**Comment by AlexSmirnov9107** [comment]
same here

package.json
```
"dependencies": {
   
    "@u4/opencv-build": "^1.0.0",
    "@u4/opencv4nodejs": "^7.0.0",
   
  },
```

**Comment by UrielCh** [comment]
you can remove:
   "opencvIncludeDir": "/opt/homebrew/Cellar/opencv/4.9.0_6/include/opencv4/",
    "opencvLibDir": "/opt/homebrew/Cellar/opencv/4.9.0_6/lib/",
    "opencvBinDir": "/opt/homebrew/Cellar/opencv/4.9.0_6/bin/"

homebrew's openCV is autodetect, on MacOS.

**Comment by AlexSmirnov9107** [comment]
> you can remove: "opencvIncludeDir": "/opt/homebrew/Cellar/opencv/4.9.0_6/include/opencv4/", "opencvLibDir": "/opt/homebrew/Cellar/opencv/4.9.0_6/lib/", "opencvBinDir": "/opt/homebrew/Cellar/opencv/4.9.0_6/bin/"
> 
> homebrew's openCV is autodetect, on MacOS, that one of the main differences with the original project.

did not help


<img width="1200" alt="image" src="https://github.com/UrielCh/opencv4nodejs/assets/32673518/d5353519-bc97-4829-8eeb-7095c3e45d27">
```
info config found opencv4nodejs section in /Users/alexandrsmirnov/Work/lombard-white/nestjs-lombard-terminal/package.json
info init no_autobuild is set.
info init 
info applyEnvsFromPackageJson the following opencv4nodejs environment variables are set in the package.json:

/Users/alexandrsmirnov/Work/lombard-white/nestjs-lombard-terminal/node_modules/@u4/opencv-build/script/deps/jsr.io/@std/fmt/0.223.0/colors.js:119
        ? `${code.open}${str.replace(code.regexp, code.open)}${code.close}`
                             ^
TypeError: str.replace is not a function
    at run (/Users/alexandrsmirnov/Work/lombard-white/nestjs-lombard-terminal/node_modules/@u4/opencv-build/script/deps/jsr.io/@std/fmt/0.223.0/colors.js:119:30)
    at Object.green (/Users/alexandrsmirnov/Work/lombard-white/nestjs-lombard-terminal/node_modules/@u4/opencv-build/script/deps/jsr.io/@std/fmt/0.223.0/colors.js:210:12)
    at formatNumber (/Users/alexandrsmirnov/Work/lombard-white/nestjs-lombard-terminal/node_modules/@u4/opencv-build/script/src/utils.js:67:43)
    at /Users/alexandrsmirnov/Work/lombard-white/nestjs-lombard-terminal/node_modules/@u4/opencv-build/script/src/OpenCVBuildEnv.js:396:161
    at Array.forEach (<anonymous>)
    at new OpenCVBuildEnv (/Users/alexandrsmirnov/Work/lombard-white/nestjs-lombard-terminal/node_modules/@u4/opencv-build/script/src/OpenCVBuildEnv.js:396:21)
    at new OpenCVBuilder (/Users/alexandrsmirnov/Work/lombard-white/nestjs-lombard-terminal/node_modules/@u4/opencv-build/script/src/OpenCVBuilder.js:75:24)
    at getOpenCV (/Users/alexandrsmirnov/Work/lombard-white/nestjs-lombard-terminal/node_modules/@u4/opencv4nodejs/cjs/lib/cvloader.js:40:21)
    at loadOpenCV (/Users/alexandrsmirnov/Work/lombard-white/nestjs-lombard-terminal/node_modules/@u4/opencv4nodejs/cjs/lib/opencv4nodejs.js:36:48)
    at Object.<anonymous> (/Users/alexandrsmirnov/Work/lombard-white/nestjs-lombard-terminal/node_modules/@u4/opencv4nodejs/cjs/lib/opencv4nodejs.js:58:14)
```

**Comment by AlexSmirnov9107** [comment]
i've figured out. 
instead of 
```
  "opencv4nodejs": {
    "disableAutoBuild": 1
  }
  ```
  
  i made
  ```
    "opencv4nodejs": {
    "disableAutoBuild": "1"
  }
  ```
  
replace number to  string

**Comment by AlexSmirnov9107** [comment]
```
info applyEnvsFromPackageJson disableAutoBuild: 1
/Users/alexandrsmirnov/Work/lombard-white/nestjs-lombard-terminal/node_modules/@u4/opencv4nodejs/build/Release/opencv4nodejs
Error: Module did not self-register: '/Users/alexandrsmirnov/Work/lombard-white/nestjs-lombard-terminal/node_modules/@u4/opencv4nodejs/build/Release/opencv4nodejs.node'.
Error: Module did not self-register: '/Users/alexandrsmirnov/Work/lombard-white/nestjs-lombard-terminal/node_modules/@u4/opencv4nodejs/build/Release/opencv4nodejs.node'.
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1464:18)
    at Module.load (node:internal/modules/cjs/loader:1205:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1021:12)
    at Module.require (node:internal/modules/cjs/loader:1230:19)
    at require (node:internal/modules/helpers:179:18)
    at getOpenCV (/Users/alexandrsmirnov/Work/lombard-white/nestjs-lombard-terminal/node_modules/@u4/opencv4nodejs/cjs/lib/cvloader.js:56:50)
    at loadOpenCV (/Users/alexandrsmirnov/Work/lombard-white/nestjs-lombard-terminal/node_modules/@u4/opencv4nodejs/cjs/lib/opencv4nodejs.js:36:48)
    at Object.<anonymous> (/Users/alexandrsmirnov/Work/lombard-white/nestjs-lombard-terminal/node_modules/@u4/opencv4nodejs/cjs/lib/opencv4nodejs.js:58:14)
    at Module._compile (node:internal/modules/cjs/loader:1368:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1426:10)




```

**Comment by jay-gaojing** [comment]
> 我已经弄清楚了。 代替
> 
> ```
>   "opencv4nodejs": {
>     "disableAutoBuild": 1
>   }
> ```
> 
> 我做了
> 
> ```
>   "opencv4nodejs": {
>   "disableAutoBuild": "1"
> }
> ```
> 
> 将数字替换为字符串

I tried to do that, but reported other errors
![image](https://github.com/UrielCh/opencv4nodejs/assets/64359368/e47a941f-dd2b-4c2a-9587-bf78e8e5bead)

**Comment by UrielCh** [comment]
fixed in within @u4/opencv-build@1.0.1
thx for the report
