### ISSUE TITLE
Errors when installing

### ISSUE THREAD

**Issue by RossNE99** [UrielCh/opencv4nodejs#144]
when running npm install --save @u4/opencv4nodejs  i get this error

windows 11
Node 18.13.0
python  3.12.4
various diffrent versions of windows build tools
node-gyp installed globaly

I have tried ,
  "opencv4nodejs": {
  "disableAutoBuild": "1"
} in the package.json and as a env variable and this just gives the same result

I know its trying to build because it takes about 10 mins to get this error after running the command and my CPU usage is high

npm WARN deprecated npmlog@7.0.1: This package is no longer supported.
npm WARN deprecated @humanwhocodes/config-array@0.11.14: Use @eslint/config-array instead
npm WARN deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm WARN deprecated are-we-there-yet@4.0.2: This package is no longer supported.
npm WARN deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
npm WARN deprecated gauge@5.0.2: This package is no longer supported.
npm ERR! code 1
npm ERR! path C:\Users\Ross\repos\test\node_modules\@u4\opencv4nodejs
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp rebuild
npm ERR!
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@10.1.0
npm ERR! gyp info using node@18.13.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.12.4 found at "C:\Python312\python.exe"
npm ERR! gyp info find VS using VS2022 (17.10.35013.160) found at:
npm ERR! gyp info find VS "C:\Program Files\Microsoft Visual Studio\2022\Community"
npm ERR! gyp info find VS run with --verbose for detailed information
npm ERR! gyp info spawn C:\Python312\python.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args 'C:\\Users\\Ross\\repos\\test\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args 'binding.gyp',
npm ERR! gyp info spawn args '-f',
npm ERR! gyp info spawn args 'msvs',
npm ERR! gyp info spawn args '-I',
npm ERR! gyp info spawn args 'C:\\Users\\Ross\\repos\\test\\node_modules\\@u4\\opencv4nodejs\\build\\config.gypi',
npm ERR! gyp info spawn args '-I',
npm ERR! gyp info spawn args 'C:\\Users\\Ross\\repos\\test\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args '-I',
npm ERR! gyp info spawn args 'C:\\Users\\Ross\\AppData\\Local\\node-gyp\\Cache\\18.13.0\\include\\node\\common.gypi',
npm ERR! gyp info spawn args '-Dlibrary=shared_library',
npm ERR! gyp info spawn args '-Dvisibility=default',
npm ERR! gyp info spawn args '-Dnode_root_dir=C:\\Users\\Ross\\AppData\\Local\\node-gyp\\Cache\\18.13.0',
npm ERR! gyp info spawn args '-Dnode_gyp_dir=C:\\Users\\Ross\\repos\\test\\node_modules\\node-gyp',
npm ERR! gyp info spawn args '-Dnode_lib_file=C:\\\\Users\\\\Ross\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\18.13.0\\\\<(target_arch)\\\\node.lib',
npm ERR! gyp info spawn args '-Dmodule_root_dir=C:\\Users\\Ross\\repos\\test\\node_modules\\@u4\\opencv4nodejs',
npm ERR! gyp info spawn args '-Dnode_engine=v8',
npm ERR! gyp info spawn args '--depth=.',
npm ERR! gyp info spawn args '--no-parallel',
npm ERR! gyp info spawn args '--generator-output',
npm ERR! gyp info spawn args 'C:\\Users\\Ross\\repos\\test\\node_modules\\@u4\\opencv4nodejs\\build',
npm ERR! gyp info spawn args '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! Traceback (most recent call last):
npm ERR!   File "C:\Users\Ross\repos\test\node_modules\node-gyp\gyp\gyp_main.py", line 45, in <module>
npm ERR!     sys.exit(gyp.script_main())
npm ERR!              ^^^^^^^^^^^^^^^^^
npm ERR!   File "C:\Users\Ross\repos\test\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 688, in script_main
npm ERR!     return main(sys.argv[1:])
npm ERR!            ^^^^^^^^^^^^^^^^^^
npm ERR!   File "C:\Users\Ross\repos\test\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 680, in main
npm ERR!     return gyp_main(args)
npm ERR!            ^^^^^^^^^^^^^^
npm ERR!   File "C:\Users\Ross\repos\test\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 647, in gyp_main
npm ERR!     [generator, flat_list, targets, data] = Load(
npm ERR!                                             ^^^^^
npm ERR!   File "C:\Users\Ross\repos\test\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 157, in Load
npm ERR!     result = gyp.input.Load(
npm ERR!              ^^^^^^^^^^^^^^^
npm ERR!   File "C:\Users\Ross\repos\test\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 2985, in Load
npm ERR!     LoadTargetBuildFile(
npm ERR!   File "C:\Users\Ross\repos\test\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 427, in LoadTargetBuildFile
npm ERR!     ProcessVariablesAndConditionsInDict(
npm ERR!   File "C:\Users\Ross\repos\test\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 1399, in ProcessVariablesAndConditionsInDict
npm ERR!     ProcessVariablesAndConditionsInList(value, phase, variables, build_file)
npm ERR!   File "C:\Users\Ross\repos\test\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 1412, in ProcessVariablesAndConditionsInList
npm ERR!     ProcessVariablesAndConditionsInDict(item, phase, variables, build_file)
npm ERR!   File "C:\Users\Ross\repos\test\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 1399, in ProcessVariablesAndConditionsInDict
npm ERR!     ProcessVariablesAndConditionsInList(value, phase, variables, build_file)
npm ERR!   File "C:\Users\Ross\repos\test\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 1416, in ProcessVariablesAndConditionsInList
npm ERR!     expanded = ExpandVariables(item, phase, variables, build_file)
npm ERR!                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
npm ERR!   File "C:\Users\Ross\repos\test\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 1050, in ExpandVariables
npm ERR!     output = shlex.split(str(replacement))
npm ERR!              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
npm ERR!   File "C:\Python312\Lib\shlex.py", line 313, in split
npm ERR!     return list(lex)
npm ERR!            ^^^^^^^^^
npm ERR!   File "C:\Python312\Lib\shlex.py", line 300, in __next__
npm ERR!     token = self.get_token()
npm ERR!             ^^^^^^^^^^^^^^^^
npm ERR!   File "C:\Python312\Lib\shlex.py", line 109, in get_token
npm ERR!     raw = self.read_token()
npm ERR!           ^^^^^^^^^^^^^^^^^
npm ERR!   File "C:\Python312\Lib\shlex.py", line 191, in read_token
npm ERR!     raise ValueError("No closing quotation")
npm ERR! ValueError: No closing quotation while trying to load binding.gyp
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack at ChildProcess.<anonymous> (C:\Users\Ross\repos\test\node_modules\node-gyp\lib\configure.js:297:18)
npm ERR! gyp ERR! stack at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Windows_NT 10.0.22631
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Ross\\repos\\test\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Users\Ross\repos\test\node_modules\@u4\opencv4nodejs
npm ERR! gyp ERR! node -v v18.13.0
npm ERR! gyp ERR! node-gyp -v v10.1.0
npm ERR! gyp ERR! not ok

**Comment by RossNE99** [comment]
Fixed - Downgraded to Python 3.10
