### ISSUE TITLE
npm error gyp ERR! configure error

### ISSUE THREAD

**Issue by tinywolf3** [UrielCh/opencv4nodejs#159]
I'm getting an error during installation.
```sh
❯ npm i @u4/opencv4nodejs
npm error code 1
npm error path /home/tinywolf/test-cv/node_modules/@u4/opencv4nodejs
npm error command failed
npm error command sh -c node-gyp rebuild
npm error gyp info it worked if it ends with ok
npm error gyp info using node-gyp@10.2.0
npm error gyp info using node@20.15.1 | linux | x64
npm error gyp info find Python using Python version 3.10.12 found at "/usr/bin/python3"
npm error gyp info spawn /usr/bin/python3
npm error gyp info spawn args [
npm error gyp info spawn args '/home/tinywolf/test-cv/node_modules/@u4/opencv4nodejs/node_modules/node-gyp/gyp/gyp_main.py',
npm error gyp info spawn args 'binding.gyp',
npm error gyp info spawn args '-f',
npm error gyp info spawn args 'make',
npm error gyp info spawn args '-I',
npm error gyp info spawn args '/home/tinywolf/test-cv/node_modules/@u4/opencv4nodejs/build/config.gypi',
npm error gyp info spawn args '-I',
npm error gyp info spawn args '/home/tinywolf/test-cv/node_modules/@u4/opencv4nodejs/node_modules/node-gyp/addon.gypi',
npm error gyp info spawn args '-I',
npm error gyp info spawn args '/home/tinywolf/.cache/node-gyp/20.15.1/include/node/common.gypi',
npm error gyp info spawn args '-Dlibrary=shared_library',
npm error gyp info spawn args '-Dvisibility=default',
npm error gyp info spawn args '-Dnode_root_dir=/home/tinywolf/.cache/node-gyp/20.15.1',
npm error gyp info spawn args '-Dnode_gyp_dir=/home/tinywolf/test-cv/node_modules/@u4/opencv4nodejs/node_modules/node-gyp',
npm error gyp info spawn args '-Dnode_lib_file=/home/tinywolf/.cache/node-gyp/20.15.1/<(target_arch)/node.lib',
npm error gyp info spawn args '-Dmodule_root_dir=/home/tinywolf/test-cv/node_modules/@u4/opencv4nodejs',
npm error gyp info spawn args '-Dnode_engine=v8',
npm error gyp info spawn args '--depth=.',
npm error gyp info spawn args '--no-parallel',
npm error gyp info spawn args '--generator-output',
npm error gyp info spawn args 'build',
npm error gyp info spawn args '-Goutput_dir=.'
npm error gyp info spawn args ]
npm error gyp: Call to 'node ./bin/install.js OPENCV4NODEJS_DEFINES' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
npm error gyp ERR! configure error 
npm error gyp ERR! stack Error: `gyp` failed with exit code: 1
npm error gyp ERR! stack at ChildProcess.<anonymous> (/home/tinywolf/test-cv/node_modules/@u4/opencv4nodejs/node_modules/node-gyp/lib/configure.js:317:18)
npm error gyp ERR! stack at ChildProcess.emit (node:events:519:28)
npm error gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:294:12)
npm error gyp ERR! System Linux 6.8.0-40-generic
npm error gyp ERR! command "/home/tinywolf/.nvm/versions/node/v20.15.1/bin/node" "/home/tinywolf/test-cv/node_modules/@u4/opencv4nodejs/node_modules/.bin/node-gyp" "rebuild"
npm error gyp ERR! cwd /home/tinywolf/test-cv/node_modules/@u4/opencv4nodejs
npm error gyp ERR! node -v v20.15.1
npm error gyp ERR! node-gyp -v v10.2.0
npm error gyp ERR! not ok
npm error A complete log of this run can be found in: /home/tinywolf/.npm/_logs/2024-09-04T11_47_23_055Z-debug-0.log
```

Occurs on ubuntu 22.04 and macbook air m1 14.6.1

```sh
❯ OPENCV4NODEJS_DISABLE_AUTOBUILD=1 npm i @u4/opencv4nodejs
npm error code 1
npm error path /home/tinywolf/test-cv/node_modules/@u4/opencv4nodejs
npm error command failed
npm error command sh -c node-gyp rebuild
npm error gyp info it worked if it ends with ok
npm error gyp info using node-gyp@10.2.0
npm error gyp info using node@20.15.1 | linux | x64
npm error gyp info find Python using Python version 3.10.12 found at "/usr/bin/python3"
npm error gyp info spawn /usr/bin/python3
npm error gyp info spawn args [
npm error gyp info spawn args '/home/tinywolf/test-cv/node_modules/@u4/opencv4nodejs/node_modules/node-gyp/gyp/gyp_main.py',
npm error gyp info spawn args 'binding.gyp',
npm error gyp info spawn args '-f',
npm error gyp info spawn args 'make',
npm error gyp info spawn args '-I',
npm error gyp info spawn args '/home/tinywolf/test-cv/node_modules/@u4/opencv4nodejs/build/config.gypi',
npm error gyp info spawn args '-I',
npm error gyp info spawn args '/home/tinywolf/test-cv/node_modules/@u4/opencv4nodejs/node_modules/node-gyp/addon.gypi',
npm error gyp info spawn args '-I',
npm error gyp info spawn args '/home/tinywolf/.cache/node-gyp/20.15.1/include/node/common.gypi',
npm error gyp info spawn args '-Dlibrary=shared_library',
npm error gyp info spawn args '-Dvisibility=default',
npm error gyp info spawn args '-Dnode_root_dir=/home/tinywolf/.cache/node-gyp/20.15.1',
npm error gyp info spawn args '-Dnode_gyp_dir=/home/tinywolf/test-cv/node_modules/@u4/opencv4nodejs/node_modules/node-gyp',
npm error gyp info spawn args '-Dnode_lib_file=/home/tinywolf/.cache/node-gyp/20.15.1/<(target_arch)/node.lib',
npm error gyp info spawn args '-Dmodule_root_dir=/home/tinywolf/test-cv/node_modules/@u4/opencv4nodejs',
npm error gyp info spawn args '-Dnode_engine=v8',
npm error gyp info spawn args '--depth=.',
npm error gyp info spawn args '--no-parallel',
npm error gyp info spawn args '--generator-output',
npm error gyp info spawn args 'build',
npm error gyp info spawn args '-Goutput_dir=.'
npm error gyp info spawn args ]
npm error /home/tinywolf/test-cv/node_modules/@u4/opencv-build/script/src/helper/detect.js:115
npm error         const [candidate] = (0, glob_1.globSync)(lookup);
npm error                                                 ^
npm error
npm error TypeError: (0 , glob_1.globSync) is not a function or its return value is not iterable
npm error     at Object.detectLibDir (/home/tinywolf/test-cv/node_modules/@u4/opencv-build/script/src/helper/detect.js:115:49)
npm error     at StaticTools.autoLocatePrebuild (/home/tinywolf/test-cv/node_modules/@u4/opencv-build/script/src/StaticTools.js:78:40)
npm error     at Object.compileLib (/home/tinywolf/test-cv/node_modules/@u4/opencv4nodejs/cjs/install/compileLib.js:232:52)
npm error     at Object.<anonymous> (/home/tinywolf/test-cv/node_modules/@u4/opencv4nodejs/bin/install.js:4:12)
npm error     at Module._compile (node:internal/modules/cjs/loader:1358:14)
npm error     at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
npm error     at Module.load (node:internal/modules/cjs/loader:1208:32)
npm error     at Module._load (node:internal/modules/cjs/loader:1024:12)
npm error     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
npm error     at node:internal/main/run_main_module:28:49
npm error
npm error Node.js v20.15.1
npm error gyp: Call to 'node ./bin/install.js OPENCV4NODEJS_DEFINES' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
npm error gyp ERR! configure error 
npm error gyp ERR! stack Error: `gyp` failed with exit code: 1
npm error gyp ERR! stack at ChildProcess.<anonymous> (/home/tinywolf/test-cv/node_modules/@u4/opencv4nodejs/node_modules/node-gyp/lib/configure.js:317:18)
npm error gyp ERR! stack at ChildProcess.emit (node:events:519:28)
npm error gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:294:12)
npm error gyp ERR! System Linux 6.8.0-40-generic
npm error gyp ERR! command "/home/tinywolf/.nvm/versions/node/v20.15.1/bin/node" "/home/tinywolf/test-cv/node_modules/@u4/opencv4nodejs/node_modules/.bin/node-gyp" "rebuild"
npm error gyp ERR! cwd /home/tinywolf/test-cv/node_modules/@u4/opencv4nodejs
npm error gyp ERR! node -v v20.15.1
npm error gyp ERR! node-gyp -v v10.2.0
npm error gyp ERR! not ok
npm error A complete log of this run can be found in: /home/tinywolf/.npm/_logs/2024-09-04T11_55_11_101Z-debug-0.log
```

**Comment by GreatHongyu** [comment]
same question, one month ago till now

**Comment by ELBEQQAL94** [comment]
The issue for me on windows 11

**Comment by UrielCh** [comment]
double check the version of @u4/opencv-build
the error had been fix month ago.
and provide me the use @u4/opencv-build's version

**Comment by UrielCh** [comment]
[glob](https://www.npmjs.com/package/glob) version increase may have cause the issue, I shoudl fix the glob version.
what glob cause the issue ?

**Comment by ELBEQQAL94** [comment]
> double check the version of @u4/opencv-build the error had been fix month ago. and provide me the use @u4/opencv-build's version

I want to install the latest version

**Comment by UrielCh** [comment]
> I want to install the latest version

looks into your `node_modules` for a `glob` folder, this folder will contains a `package.json`, check the version number in this file.

that will help me to identify the issue.

**Comment by ELBEQQAL94** [comment]
It works now, Maybe after cleanup and install node-gyp should restart your local machine
Now the installation works fine

**Comment by ELBEQQAL94** [comment]
@UrielCh Thanks!

**Comment by ELBEQQAL94** [comment]
Hello @UrielCh again, Sorry but I have other issue
My current issue when I try to run the js file with "node ./main.js" I get this error:
TypeError: cv.imread is not a function

There is an extra step I missed?

Thanks!

**Comment by UrielCh** [comment]
> Hello @UrielCh again, Sorry but I have other issue My current issue when I try to run the js file with "node ./main.js" I get this error: TypeError: cv.imread is not a function
> 
> There is an extra step I missed?
> 
> Thanks!

more context ?

**Comment by ELBEQQAL94** [comment]
@UrielCh , Sorry I was trying the wrong model which is "@u4/opencv-build", But in fact when I relized that I switch to the correct model which is what I want to install in the first time "@u4/opencv4nodejs" and I got node-gyp error and this the issue I get last week.
Sorry about the confusion if you have more questions feel free to ask me
Thanks for support again
