### ISSUE TITLE
How to run build-opencv ?

### ISSUE THREAD

**Issue by Azperin** [UrielCh/opencv4nodejs#17]
I have install `npm install opencv-build`, but how to launch opencv-build-npm ? build-opencv command not found
```
R:\gitproj\openCV\node_modules\@u4\opencv-build\lib\BuildEnv.js:92
                throw Error(`No build found in ${this.rootDir} you should launch opencv-build-npm once`);
                ^

Error: No build found in R:\gitproj\openCV\node_modules\@u4\opencv-build you should launch opencv-build-npm once
    at new OpenCVBuildEnv (R:\gitproj\openCV\node_modules\@u4\opencv-build\lib\BuildEnv.js:92:23)
    at new OpenCVBuilder (R:\gitproj\openCV\node_modules\@u4\opencv-build\lib\OpenCVBuilder.js:49:24)
    at getOpenCV (R:\gitproj\openCV\node_modules\@u4\opencv4nodejs\lib\cvloader.js:16:21)
    at loadOpenCV (R:\gitproj\openCV\node_modules\@u4\opencv4nodejs\lib\opencv4nodejs.js:9:43)
    at Object.<anonymous> (R:\gitproj\openCV\node_modules\@u4\opencv4nodejs\lib\opencv4nodejs.js:24:12)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)

Node.js v17.8.0
```

*OpenCV version* (example 3.4.1): 4.5.5

*OS*: Windows 10?

**Comment by Azperin** [comment]
> 

opencv-build-npm command not found, that was the problem. I using justadude version, good enough for now

**Comment by UrielCh** [comment]
small nodeJS lesson:
*NodeJS* scripts are installed in node_modules/.bin by your package manager usually `npm`.
so include `./node_modules/.bin` in your `$PATH` environment variable, or prefix `opencv-build-npm` by `./node_modules/.bin/`

All command present in the "script" part of your package.json are called including `./node_modules/.bin` in they `$PATH`.

I should include that in the error message.
