### ISSUE TITLE
primordials is not defined

### ISSUE THREAD

**Issue by piercus** [UrielCh/opencv4nodejs#24]
While running
```
npx build-opencv rebuild 
```
I'm facing
```
info config no opencv4nodejs section found in /home/pierre/dev/lib-node-pnp-assignement/package.json
info init no openCV version given using default verison 4.5.4
info init Workdir will be: /home/pierre/opencv/opencv-4.5.4
info install Using openCV 4.5.4
info install Using lib dir: /home/pierre/opencv/opencv-4.5.4/build/lib
info install 
info install Found the following libs:
info install core: /home/pierre/opencv/opencv-4.5.4/build/lib/libopencv_core.so.4.5.4
info install highgui: /home/pierre/opencv/opencv-4.5.4/build/lib/libopencv_highgui.so.4.5.4
info install imgcodecs: /home/pierre/opencv/opencv-4.5.4/build/lib/libopencv_imgcodecs.so.4.5.4
info install imgproc: /home/pierre/opencv/opencv-4.5.4/build/lib/libopencv_imgproc.so.4.5.4
info install features2d: /home/pierre/opencv/opencv-4.5.4/build/lib/libopencv_features2d.so.4.5.4
info install calib3d: /home/pierre/opencv/opencv-4.5.4/build/lib/libopencv_calib3d.so.4.5.4
info install photo: /home/pierre/opencv/opencv-4.5.4/build/lib/libopencv_photo.so.4.5.4
info install objdetect: /home/pierre/opencv/opencv-4.5.4/build/lib/libopencv_objdetect.so.4.5.4
info install ml: /home/pierre/opencv/opencv-4.5.4/build/lib/libopencv_ml.so.4.5.4
info install video: /home/pierre/opencv/opencv-4.5.4/build/lib/libopencv_video.so.4.5.4
info install videoio: /home/pierre/opencv/opencv-4.5.4/build/lib/libopencv_videoio.so.4.5.4
info install videostab: /home/pierre/opencv/opencv-4.5.4/build/lib/libopencv_videostab.so.4.5.4
info install dnn: /home/pierre/opencv/opencv-4.5.4/build/lib/libopencv_dnn.so.4.5.4
info install face: /home/pierre/opencv/opencv-4.5.4/build/lib/libopencv_face.so.4.5.4
info install text: /home/pierre/opencv/opencv-4.5.4/build/lib/libopencv_text.so.4.5.4
info install tracking: /home/pierre/opencv/opencv-4.5.4/build/lib/libopencv_tracking.so.4.5.4
info install xfeatures2d: /home/pierre/opencv/opencv-4.5.4/build/lib/libopencv_xfeatures2d.so.4.5.4
info install ximgproc: /home/pierre/opencv/opencv-4.5.4/build/lib/libopencv_ximgproc.so.4.5.4
info defines 
info defines Setting the following defines:
info defines OPENCV4NODEJS_FOUND_LIBRARY_CORE        OPENCV4NODEJS_FOUND_LIBRARY_HIGHGUI     OPENCV4NODEJS_FOUND_LIBRARY_IMGCODECS   
info defines OPENCV4NODEJS_FOUND_LIBRARY_IMGPROC     OPENCV4NODEJS_FOUND_LIBRARY_FEATURES2D  OPENCV4NODEJS_FOUND_LIBRARY_CALIB3D     
info defines OPENCV4NODEJS_FOUND_LIBRARY_PHOTO       OPENCV4NODEJS_FOUND_LIBRARY_OBJDETECT   OPENCV4NODEJS_FOUND_LIBRARY_ML          
info defines OPENCV4NODEJS_FOUND_LIBRARY_VIDEO       OPENCV4NODEJS_FOUND_LIBRARY_VIDEOIO     OPENCV4NODEJS_FOUND_LIBRARY_VIDEOSTAB   
info defines OPENCV4NODEJS_FOUND_LIBRARY_DNN         OPENCV4NODEJS_FOUND_LIBRARY_FACE        OPENCV4NODEJS_FOUND_LIBRARY_TEXT        
info defines OPENCV4NODEJS_FOUND_LIBRARY_TRACKING    OPENCV4NODEJS_FOUND_LIBRARY_XFEATURES2D OPENCV4NODEJS_FOUND_LIBRARY_XIMGPROC    
info install 
info install Setting the following includes:
info includes /home/pierre/opencv/opencv-4.5.4/build/include
info includes /home/pierre/opencv/opencv-4.5.4/build/include/opencv4
info libs 
info libs Setting lib from -L/home/pierre/opencv/opencv-4.5.4/build : lib, -lopencv_core, -lopencv_highgui, -lopencv_imgcodecs, -lopencv_imgproc, -lopencv_features2d, -lopencv_calib3d, -lopencv_photo, -lopencv_objdetect, -lopencv_ml, -lopencv_video, -lopencv_videoio, -lopencv_videostab, -lopencv_dnn, -lopencv_face, -lopencv_text, -lopencv_tracking, -lopencv_xfeatures2d, -lopencv_ximgproc, lib
info install Spawning in directory:/home/pierre/dev/lib-node-pnp-assignement/node_modules/@u4/opencv4nodejs node-gyp process: node-gyp rebuild --jobs max --release 
evalmachine.<anonymous>:36
} = primordials;
    ^

ReferenceError: primordials is not defined
    at evalmachine.<anonymous>:36:5
    at Object.<anonymous> (/home/pierre/.npm-packages/lib/node_modules/node-gyp/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/pierre/.npm-packages/lib/node_modules/node-gyp/node_modules/graceful-fs/graceful-fs.js:3:27)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
error:  Error: Command failed: node-gyp rebuild --jobs max --release 
evalmachine.<anonymous>:36
} = primordials;
    ^

ReferenceError: primordials is not defined
    at evalmachine.<anonymous>:36:5
    at Object.<anonymous> (/home/pierre/.npm-packages/lib/node_modules/node-gyp/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/pierre/.npm-packages/lib/node_modules/node-gyp/node_modules/graceful-fs/graceful-fs.js:3:27)
    at Module._compile (internal/modules/cjs/loader.js:999:30)

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'node-gyp rebuild --jobs max --release '
}
ERR! install node-gyp failed and return Error Command failed: node-gyp rebuild --jobs max --release 
ERR! install evalmachine.<anonymous>:36
ERR! install } = primordials;
ERR! install     ^
ERR! install 
ERR! install ReferenceError: primordials is not defined
ERR! install     at evalmachine.<anonymous>:36:5
ERR! install     at Object.<anonymous> (/home/pierre/.npm-packages/lib/node_modules/node-gyp/node_modules/graceful-fs/fs.js:11:1)
ERR! install     at Module._compile (internal/modules/cjs/loader.js:999:30)
ERR! install     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
ERR! install     at Module.load (internal/modules/cjs/loader.js:863:32)
ERR! install     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
ERR! install     at Module.require (internal/modules/cjs/loader.js:887:19)
ERR! install     at require (internal/modules/cjs/helpers.js:74:18)
ERR! install     at Object.<anonymous> (/home/pierre/.npm-packages/lib/node_modules/node-gyp/node_modules/graceful-fs/graceful-fs.js:3:27)
ERR! install     at Module._compile (internal/modules/cjs/loader.js:999:30)
ERR! install  return code: 1
```
Node version
```
node -v
v12.20.1
```

**Comment by piercus** [comment]
Problem with node-gyp

```
npm install -g node-gyp
```
Fixed it
