### ISSUE TITLE
Cannot build opencv4nodejs in a docker container

### ISSUE THREAD

**Issue by V-kto** [UrielCh/opencv4nodejs#27]
Hello there :wave:

I create this issue as a result of [this](https://github.com/UrielCh/opencv4nodejs/issues/16#issuecomment-1117184722)

We need to install `opencv4nodejs` on a docker image. The goal is to deploy this image on an AWS lambda.
We have some troubles with the command `yarn opencv-build`

# Environment

MacOSX `12.3.1`
Docker desktop `4.7.1`

### Dockerfile

> This Dockerfile was written for the issue and is not optimized.

```dockerfile
FROM amazonlinux:2

WORKDIR /tmp

RUN yum install -y git

RUN git clone https://github.com/opencv/opencv.git

RUN yum groupinstall -y "Development Tools"
RUN yum install -y cmake3 

WORKDIR /tmp/myproject/opencv_build

RUN cmake3 -D CMAKE_BUILD_TYPE:STRING=Release -D BUILD_LIST=core,imgproc,imgcodecs /tmp/opencv

RUN cmake3 --build .

RUN touch ~/.bashrc

RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash

WORKDIR /tmp/myproject

RUN touch package.json test.js

RUN echo '{"license": "MIT"}' > package.json

RUN source ~/.bashrc ; nvm install 14 ; nvm use 14 ; npm install --global yarn ; yarn add @u4/opencv4nodejs

RUN echo 'var __importDefault = (this && this.__importDefault) || function (mod) { \
  return (mod && mod.__esModule) ? mod : { "default": mod }; \
  }; \
  const opencv4nodejs_1 = __importDefault(require("@u4/opencv4nodejs")); \
  const getOpenCV = () => ({ \
  ...opencv4nodejs_1.default, \
  /** \
  * Call this function in debugger to close all windows opened w/ cv.imwshowWait on MacOS \
  */ \
  closeDebugWindows: () => { \
  opencv4nodejs_1.default.destroyAllWindows(); \
  opencv4nodejs_1.default.waitKey(1); \
  }, \
  });' \
  > test.js

RUN yum install -y cmake

# source ~/.bashrc
# export npm_config_node_gyp=/root/.nvm/versions/node/v14.19.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin/node-gyp
# yarn build-opencv --incDir /tmp/myproject/opencv_build/include --libDir /tmp/myproject/opencv_build/lib --binDir /tmp/myproject/opencv_build/bin build

```

# How to reproduce the error

- Create a Dockerfile with the above content
- Build the image docker `build /path-to-Dockerfile`
- Run the container
- Go into the container with `docker exec -it <container-id> /bin/sh` and run the following
  - `source ~/.bashrc`
  - `export npm_config_node_gyp=/root/.nvm/versions/node/v14.19.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin/node-gyp`
  - `yarn build-opencv --incDir /tmp/myproject/opencv_build/include --libDir /tmp/myproject/opencv_build/lib --binDir /tmp/myproject/opencv_build/bin build`

# Error Message

```shell
Error response from daemon: Bad response from Docker engine
```
![Screenshot 2022-05-04 at 15 58 27](https://user-images.githubusercontent.com/83078410/166707306-ebd8df4f-f75f-4632-9fda-4dea42bf82d1.png)

In the container if you try to run `node test.js` you will have the following error : 
```shell
info config no opencv4nodejs section found in /tmp/myproject/package.json
/tmp/myproject/node_modules/@u4/opencv-build/lib/BuildEnv.js:109
                throw Error(`No build found in ${this.rootDir} you should launch opencv-build-npm once`);
                ^

Error: No build found in /tmp/myproject/node_modules/@u4/opencv-build you should launch opencv-build-npm once
    at new OpenCVBuildEnv (/tmp/myproject/node_modules/@u4/opencv-build/lib/BuildEnv.js:109:23)
    at new OpenCVBuilder (/tmp/myproject/node_modules/@u4/opencv-build/lib/OpenCVBuilder.js:53:24)
    at getOpenCV (/tmp/myproject/node_modules/@u4/opencv4nodejs/lib/cvloader.js:15:21)
    at loadOpenCV (/tmp/myproject/node_modules/@u4/opencv4nodejs/lib/opencv4nodejs.js:9:43)
    at Object.<anonymous> (/tmp/myproject/node_modules/@u4/opencv4nodejs/lib/opencv4nodejs.js:24:12)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
```

Thank you for your help and contribution 🥰

**Comment by UrielCh** [comment]
Still no docker this week.
I can not test it now.

**Comment by UrielCh** [comment]
I'm in my Kubernetes Month.

@u4/opencv4nodejs 6.2.4 is out.

Used in my docker image AMD64 and ARM64

a NestJS + openCV sample:

```
FROM node:18 As build

WORKDIR /usr/src/app
RUN apt update && apt -y upgrade && apt -y install libopencv-contrib-dev libopencv-dev
COPY package*.json pnpm-lock.yaml tsconfig.* src ./
RUN npm install -g rimraf
RUN npm install --no-fund
ENV OPENCV4NODEJS_DISABLE_AUTOBUILD=1
RUN npx build-opencv rebuild
RUN rimraf src
RUN rimraf node_modules/**/*.{md,ts,map,h,c,cc,cpp,gyp,yml,so,txt}
RUN rimraf node_modules/{types,@eslint}
RUN rimraf node_modules/**/{LICENSE,.github,.npmignore,LICENSE.txt,.travis.yml,.eslintrc,sponsors}
RUN rimraf node_modules/*/{test,binding.gyp}
RUN find . -type f -empty -print -delete
RUN find . -type d -empty -print -delete

FROM node:18 As production
ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}
WORKDIR /usr/src/app
RUN apt update && apt -y upgrade && apt -y install libopencv-contrib-dev libopencv-dev && rm -rf /var/lib/apt/lists/*
COPY --from=build /usr/src/app /usr/src/app

CMD ["node", "dist/main"]
```

**Comment by UrielCh** [comment]
[@u4/opencv-nodejs Docker image is out](https://hub.docker.com/r/urielch/opencv-nodejs)
available for AMD64 and ARM64
