### ISSUE TITLE
wont build on macos

### ISSUE THREAD

**Issue by farfromrefug** [UrielCh/opencv4nodejs#28]
Node: v16.14.2
python: 3.9.7
node-gyp: 9.0.0

I try to use your package but i cant get it to work.
So i add the package, run `npm i` 
then i run `./node_modules/.bin/build-opencv build` but am faced with 
```
ERR! install gyp ERR! stack Error: You must run `node-gyp configure` first!
```
I am using `node-gyp` 9.0.0.(also tried with 8.4.1).
Now i can get around this one by running `node-gyp configure` in `node_modules/@u4/opencv4nodejs`

But then if i run `./node_modules/.bin/build-opencv build` again the build fail by not finding opencv2 includes as shown below.
It does the same if using autobuild or not.
I have checked `OPENCV4NODEJS_INCLUDES` env and it is good. I know it is passed to node-gyp.
i also tried to run `node ./install/parseEnv.js OPENCV4NODEJS_INCLUDES` and it does correctly return `/usr/local/include/opencv4` which contains an `opencv2` folder.
Would you have any idea?
```
info config found opencv4nodejs section in /Volumes/dev/nativescript/jule_verne/script_tests/package.json
info applyEnvsFromPackageJson the following opencv4nodejs environment variables are set in the package.json:
info applyEnvsFromPackageJson autoBuildFlags: -DBUILD_LIST=core,imgproc,imgcodecs,photo,highgui
info applyEnvsFromPackageJson disableAutoBuild: 1
info applyEnvsFromPackageJson opencvIncludeDir: /usr/local/include/opencv4
info applyEnvsFromPackageJson opencvLibDir: /usr/local/lib
info applyEnvsFromPackageJson opencvBinDir: /usr/local/bin
info init Workdir will be: /Volumes/dev/nativescript/jule_verne/script_tests/node_modules/@u4/opencv-build/opencv-0.0.0-75cde
info install Using openCV 0.0.0
info install Using lib dir: /usr/local/lib
info install 
info install Found the following libs:
info install core: /usr/local/Cellar/opencv/4.5.5_2/lib/libopencv_core.4.5.5.dylib
info install highgui: /usr/local/Cellar/opencv/4.5.5_2/lib/libopencv_highgui.4.5.5.dylib
info install imgcodecs: /usr/local/Cellar/opencv/4.5.5_2/lib/libopencv_imgcodecs.4.5.5.dylib
info install imgproc: /usr/local/Cellar/opencv/4.5.5_2/lib/libopencv_imgproc.4.5.5.dylib
info install features2d: /usr/local/Cellar/opencv/4.5.5_2/lib/libopencv_features2d.4.5.5.dylib
info install calib3d: /usr/local/Cellar/opencv/4.5.5_2/lib/libopencv_calib3d.4.5.5.dylib
info install photo: /usr/local/Cellar/opencv/4.5.5_2/lib/libopencv_photo.4.5.5.dylib
info install objdetect: /usr/local/Cellar/opencv/4.5.5_2/lib/libopencv_objdetect.4.5.5.dylib
info install ml: /usr/local/Cellar/opencv/4.5.5_2/lib/libopencv_ml.4.5.5.dylib
info install video: /usr/local/Cellar/opencv/4.5.5_2/lib/libopencv_video.4.5.5.dylib
info install videoio: /usr/local/Cellar/opencv/4.5.5_2/lib/libopencv_videoio.4.5.5.dylib
info install videostab: /usr/local/Cellar/opencv/4.5.5_2/lib/libopencv_videostab.4.5.5.dylib
info install dnn: /usr/local/Cellar/opencv/4.5.5_2/lib/libopencv_dnn.4.5.5.dylib
info install face: /usr/local/Cellar/opencv/4.5.5_2/lib/libopencv_face.4.5.5.dylib
info install text: /usr/local/Cellar/opencv/4.5.5_2/lib/libopencv_text.4.5.5.dylib
info install tracking: /usr/local/Cellar/opencv/4.5.5_2/lib/libopencv_tracking.4.5.5.dylib
info install xfeatures2d: /usr/local/Cellar/opencv/4.5.5_2/lib/libopencv_xfeatures2d.4.5.5.dylib
info install ximgproc: /usr/local/Cellar/opencv/4.5.5_2/lib/libopencv_ximgproc.4.5.5.dylib
info defines 
info defines Setting the following defines:
info defines OPENCV4NODEJS_FOUND_LIBRARY_CORE        OPENCV4NODEJS_FOUND_LIBRARY_HIGHGUI     OPENCV4NODEJS_FOUND_LIBRARY_IMGCODECS   
info defines OPENCV4NODEJS_FOUND_LIBRARY_IMGPROC     OPENCV4NODEJS_FOUND_LIBRARY_FEATURES2D  OPENCV4NODEJS_FOUND_LIBRARY_CALIB3D     
info defines OPENCV4NODEJS_FOUND_LIBRARY_PHOTO       OPENCV4NODEJS_FOUND_LIBRARY_OBJDETECT   OPENCV4NODEJS_FOUND_LIBRARY_ML          
info defines OPENCV4NODEJS_FOUND_LIBRARY_VIDEO       OPENCV4NODEJS_FOUND_LIBRARY_VIDEOIO     OPENCV4NODEJS_FOUND_LIBRARY_VIDEOSTAB   
info defines OPENCV4NODEJS_FOUND_LIBRARY_DNN         OPENCV4NODEJS_FOUND_LIBRARY_FACE        OPENCV4NODEJS_FOUND_LIBRARY_TEXT        
info defines OPENCV4NODEJS_FOUND_LIBRARY_TRACKING    OPENCV4NODEJS_FOUND_LIBRARY_XFEATURES2D OPENCV4NODEJS_FOUND_LIBRARY_XIMGPROC    
info install 
info install Setting the following includes:
info includes /usr/local/include/opencv4
info libs 
info libs Setting lib from -L/usr/local : lib, -lopencv_core, -lopencv_highgui, -lopencv_imgcodecs, -lopencv_imgproc, -lopencv_features2d, -lopencv_calib3d, -lopencv_photo, -lopencv_objdetect, -lopencv_ml, -lopencv_video, -lopencv_videoio, -lopencv_videostab, -lopencv_dnn, -lopencv_face, -lopencv_text, -lopencv_tracking, -lopencv_xfeatures2d, -lopencv_ximgproc, lib
info install Spawning in directory:/Volumes/dev/nativescript/jule_verne/script_tests/node_modules/@u4/opencv4nodejs node-gyp process: /Volumes/dev/nativescript/jule_verne/script_tests/node_modules/.bin/node-gyp build --jobs max --release 
gyp info it worked if it ends with ok
gyp info using node-gyp@8.4.1
gyp info using node@16.14.2 | darwin | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build', '--jobs', 16 ]
  CXX(target) Release/obj.target/opencv4nodejs/cc/opencv4nodejs.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/CustomMatAllocator.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/ExternalMemTracking.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/core/core.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/core/coreConstants.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/core/HistAxes.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/core/Mat.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/core/Point.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/core/Vec.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/core/Size.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/core/Rect.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/core/RotatedRect.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/core/TermCriteria.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/imgproc/imgproc.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/imgproc/imgprocConstants.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/imgproc/MatImgproc.o
In file included from ../cc/core/Size.cc:1:
../cc/core/Size.h:1:10: fatal error: 'opencv2/core.hpp' file not found
#include <opencv2/core.hpp>
         ^~~~~~~~~~~~~~~~~~
In file included from ../cc/core/Rect.cc:1:
../cc/core/Rect.h:1:10: fatal error: 'opencv2/core.hpp' file not found
#include <opencv2/core.hpp>
         ^~~~~~~~~~~~~~~~~~
In file included from ../cc/core/TermCriteria.cc:1:
../cc/core/TermCriteria.h:1:10: fatal error: 'opencv2/core.hpp' file not found
#include <opencv2/core.hpp>
         ^~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/opencv4nodejs/cc/core/Size.o] Error 1
make: *** Waiting for unfinished jobs....
1 error generated.
make: *** [Release/obj.target/opencv4nodejs/cc/core/TermCriteria.o] Error 1
1 error generated.
make: *** [Release/obj.target/opencv4nodejs/cc/core/Rect.o] Error 1
In file included from ../cc/core/Mat.cc:1:
In file included from ../cc/opencv_modules.h:1:
../cc/macros.h:2:10: fatal error: 'opencv2/core.hpp' file not found
#include <opencv2/core.hpp>
         ^~~~~~~~~~~~~~~~~~
In file included from ../cc/core/coreConstants.cc:1:
In file included from ../cc/core/coreConstants.h:1:
../cc/macros.h:2:10: fatal error: 'opencv2/core.hpp' file not found
#include <opencv2/core.hpp>
         ^~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/opencv4nodejs/cc/core/coreConstants.o] Error 1
In file included from ../cc/core/core.cc:1:
In file included from ../cc/core/core.h:1:
In file included from ../cc/core/Mat.h:1:
In file included from ../cc/core/coreUtils.h:1:
../cc/macros.h:2:10: fatal error: 'opencv2/core.hpp' file not found
#include <opencv2/core.hpp>
         ^~~~~~~~~~~~~~~~~~
In file included from ../cc/core/Vec.cc:1:
In file included from ../cc/core/Vec.h:1:
../cc/macros.h:2:10: fatal error: 'opencv2/core.hpp' file not found
#include <opencv2/core.hpp>
         ^~~~~~~~~~~~~~~~~~
In file included from ../cc/imgproc/imgprocConstants.cc:1:
In file included from ../cc/opencv_modules.h:1:
../cc/macros.h:2:10: fatal error: 'opencv2/core.hpp' file not found
#include <opencv2/core.hpp>
         ^~~~~~~~~~~~~~~~~~
In file included from ../cc/imgproc/imgproc.cc:1:
In file included from ../cc/opencv_modules.h:1:
../cc/macros.h:2:10: fatal error: 'opencv2/core.hpp' file not found
#include <opencv2/core.hpp>
         ^~~~~~~~~~~~~~~~~~
In file included from ../cc/core/Point.cc:1:
In file included from ../cc/core/Point.h:1:
../cc/macros.h:2:10: fatal error: 'opencv2/core.hpp' file not found
#include <opencv2/core.hpp>
         ^~~~~~~~~~~~~~~~~~
In file included from ../cc/ExternalMemTracking.cc:1:
In file included from ../cc/ExternalMemTracking.h:1:
../cc/macros.h:2:10: fatal error: 'opencv2/core.hpp' file not found
#include <opencv2/core.hpp>
         ^~~~~~~~~~~~~~~~~~
1 error generated.
1 error generated.
In file included from ../cc/core/HistAxes.cc:5:
In file included from ../cc/core/HistAxes.h:4:
../cc/macros.h:2:10: fatal error: 'opencv2/core.hpp' file not found
#include <opencv2/core.hpp>
         ^~~~~~~~~~~~~~~~~~
In file included from ../cc/core/RotatedRect.cc:1:
In file included from ../cc/core/RotatedRect.h:1:
../cc/macros.h:2:10: fatal error: 'opencv2/core.hpp' file not found
#include <opencv2/core.hpp>
         ^~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/opencv4nodejs/cc/imgproc/imgprocConstants.o] Error 1
make: *** [Release/obj.target/opencv4nodejs/cc/core/HistAxes.o] Error 1
1 error generated.
make: *** [Release/obj.target/opencv4nodejs/cc/imgproc/imgproc.o] Error 1
In file included from ../cc/imgproc/MatImgproc.cc:1:
In file included from ../cc/opencv_modules.h:1:
../cc/macros.h:2:10: fatal error: 'opencv2/core.hpp' file not found
#include <opencv2/core.hpp>
         ^~~~~~~~~~~~~~~~~~
make: *** [Release/obj.target/opencv4nodejs/cc/core/Point.o] Error 1
1 error generated.
make: *** [Release/obj.target/opencv4nodejs/cc/imgproc/MatImgproc.o] Error 1
1 error generated.
1 error generated.
make: *** [Release/obj.target/opencv4nodejs/cc/core/RotatedRect.o] Error 1
make: *** [Release/obj.target/opencv4nodejs/cc/core/Vec.o] Error 1
In file included from ../cc/opencv4nodejs.cc:2:
In file included from ../cc/ExternalMemTracking.h:1:
../cc/macros.h:2:10: fatal error: 'opencv2/core.hpp' file not found
#include <opencv2/core.hpp>
         ^~~~~~~~~~~~~~~~~~
In file included from ../cc/CustomMatAllocator.cc:1:
In file included from ../cc/CustomMatAllocator.h:8:
../cc/core/Size.h:1:10: fatal error: 'opencv2/core.hpp' file not found
#include <opencv2/core.hpp>
         ^~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/opencv4nodejs/cc/ExternalMemTracking.o] Error 1
1 error generated.
make: *** [Release/obj.target/opencv4nodejs/cc/CustomMatAllocator.o] Error 1
1 error generated.
make: *** [Release/obj.target/opencv4nodejs/cc/opencv4nodejs.o] Error 1
1 error generated.
make: *** [Release/obj.target/opencv4nodejs/cc/core/core.o] Error 1
1 error generated.
make: *** [Release/obj.target/opencv4nodejs/cc/core/Mat.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Volumes/dev/nativescript/jule_verne/script_tests/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:526:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Darwin 20.6.0
gyp ERR! command "/Volumes/data/mguillon/.nvm/versions/node/v16.14.2/bin/node" "/Volumes/dev/nativescript/jule_verne/script_tests/node_modules/.bin/node-gyp" "build" "--jobs" "max" "--release"
gyp ERR! cwd /Volumes/dev/nativescript/jule_verne/script_tests/node_modules/@u4/opencv4nodejs
gyp ERR! node -v v16.14.2
gyp ERR! node-gyp -v v8.4.1
gyp ERR! not ok 
error:  Error: Command failed: /Volumes/dev/nativescript/jule_verne/script_tests/node_modules/.bin/node-gyp build --jobs max --release 
gyp info it worked if it ends with ok
gyp info using node-gyp@8.4.1
gyp info using node@16.14.2 | darwin | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build', '--jobs', 16 ]
In file included from ../cc/core/Size.cc:1:
../cc/core/Size.h:1:10: fatal error: 'opencv2/core.hpp' file not found
#include <opencv2/core.hpp>
         ^~~~~~~~~~~~~~~~~~
In file included from ../cc/core/Rect.cc:1:
../cc/core/Rect.h:1:10: fatal error: 'opencv2/core.hpp' file not found
#include <opencv2/core.hpp>
         ^~~~~~~~~~~~~~~~~~
In file included from ../cc/core/TermCriteria.cc:1:
../cc/core/TermCriteria.h:1:10: fatal error: 'opencv2/core.hpp' file not found
#include <opencv2/core.hpp>
         ^~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/opencv4nodejs/cc/core/Size.o] Error 1
make: *** Waiting for unfinished jobs....
1 error generated.
make: *** [Release/obj.target/opencv4nodejs/cc/core/TermCriteria.o] Error 1
1 error generated.
make: *** [Release/obj.target/opencv4nodejs/cc/core/Rect.o] Error 1
In file included from ../cc/core/Mat.cc:1:
In file included from ../cc/opencv_modules.h:1:
../cc/macros.h:2:10: fatal error: 'opencv2/core.hpp' file not found
#include <opencv2/core.hpp>
         ^~~~~~~~~~~~~~~~~~
In file included from ../cc/core/coreConstants.cc:1:
In file included from ../cc/core/coreConstants.h:1:
../cc/macros.h:2:10: fatal error: 'opencv2/core.hpp' file not found
#include <opencv2/core.hpp>
         ^~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/opencv4nodejs/cc/core/coreConstants.o] Error 1
In file included from ../cc/core/core.cc:1:
In file included from ../cc/core/core.h:1:
In file included from ../cc/core/Mat.h:1:
In file included from ../cc/core/coreUtils.h:1:
../cc/macros.h:2:10: fatal error: 'opencv2/core.hpp' file not found
#include <opencv2/core.hpp>
         ^~~~~~~~~~~~~~~~~~
In file included from ../cc/core/Vec.cc:1:
In file included from ../cc/core/Vec.h:1:
../cc/macros.h:2:10: fatal error: 'opencv2/core.hpp' file not found
#include <opencv2/core.hpp>
         ^~~~~~~~~~~~~~~~~~
In file included from ../cc/imgproc/imgprocConstants.cc:1:
In file included from ../cc/opencv_modules.h:1:
../cc/macros.h:2:10: fatal error: 'opencv2/core.hpp' file not found
#include <opencv2/core.hpp>
         ^~~~~~~~~~~~~~~~~~
In file included from ../cc/imgproc/imgproc.cc:1:
In file included from ../cc/opencv_modules.h:1:
../cc/macros.h:2:10: fatal error: 'opencv2/core.hpp' file not found
#include <opencv2/core.hpp>
         ^~~~~~~~~~~~~~~~~~
In file included from ../cc/core/Point.cc:1:
In file included from ../cc/core/Point.h:1:
../cc/macros.h:2:10: fatal error: 'opencv2/core.hpp' file not found
#include <opencv2/core.hpp>
         ^~~~~~~~~~~~~~~~~~
In file included from ../cc/ExternalMemTracking.cc:1:
In file included from ../cc/ExternalMemTracking.h:1:
../cc/macros.h:2:10: fatal error: 'opencv2/core.hpp' file not found
#include <opencv2/core.hpp>
         ^~~~~~~~~~~~~~~~~~
1 error generated.
1 error generated.
In file included from ../cc/core/HistAxes.cc:5:
In file included from ../cc/core/HistAxes.h:4:
../cc/macros.h:2:10: fatal error: 'opencv2/core.hpp' file not found
#include <opencv2/core.hpp>
         ^~~~~~~~~~~~~~~~~~
In file included from ../cc/core/RotatedRect.cc:1:
In file included from ../cc/core/RotatedRect.h:1:
../cc/macros.h:2:10: fatal error: 'opencv2/core.hpp' file not found
#include <opencv2/core.hpp>
         ^~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/opencv4nodejs/cc/imgproc/imgprocConstants.o] Error 1
make: *** [Release/obj.target/opencv4nodejs/cc/core/HistAxes.o] Error 1
1 error generated.
make: *** [Release/obj.target/opencv4nodejs/cc/imgproc/imgproc.o] Error 1
In file included from ../cc/imgproc/MatImgproc.cc:1:
In file included from ../cc/opencv_modules.h:1:
../cc/macros.h:2:10: fatal error: 'opencv2/core.hpp' file not found
#include <opencv2/core.hpp>
         ^~~~~~~~~~~~~~~~~~
make: *** [Release/obj.target/opencv4nodejs/cc/core/Point.o] Error 1
1 error generated.
make: *** [Release/obj.target/opencv4nodejs/cc/imgproc/MatImgproc.o] Error 1
1 error generated.
1 error generated.
make: *** [Release/obj.target/opencv4nodejs/cc/core/RotatedRect.o] Error 1
make: *** [Release/obj.target/opencv4nodejs/cc/core/Vec.o] Error 1
In file included from ../cc/opencv4nodejs.cc:2:
In file included from ../cc/ExternalMemTracking.h:1:
../cc/macros.h:2:10: fatal error: 'opencv2/core.hpp' file not found
#include <opencv2/core.hpp>
         ^~~~~~~~~~~~~~~~~~
In file included from ../cc/CustomMatAllocator.cc:1:
In file included from ../cc/CustomMatAllocator.h:8:
../cc/core/Size.h:1:10: fatal error: 'opencv2/core.hpp' file not found
#include <opencv2/core.hpp>
         ^~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/opencv4nodejs/cc/ExternalMemTracking.o] Error 1
1 error generated.
make: *** [Release/obj.target/opencv4nodejs/cc/CustomMatAllocator.o] Error 1
1 error generated.
make: *** [Release/obj.target/opencv4nodejs/cc/opencv4nodejs.o] Error 1
1 error generated.
make: *** [Release/obj.target/opencv4nodejs/cc/core/core.o] Error 1
1 error generated.
make: *** [Release/obj.target/opencv4nodejs/cc/core/Mat.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Volumes/dev/nativescript/jule_verne/script_tests/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:526:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Darwin 20.6.0
gyp ERR! command "/Volumes/data/mguillon/.nvm/versions/node/v16.14.2/bin/node" "/Volumes/dev/nativescript/jule_verne/script_tests/node_modules/.bin/node-gyp" "build" "--jobs" "max" "--release"
gyp ERR! cwd /Volumes/dev/nativescript/jule_verne/script_tests/node_modules/@u4/opencv4nodejs
gyp ERR! node -v v16.14.2
gyp ERR! node-gyp -v v8.4.1
gyp ERR! not ok 

    at ChildProcess.exithandler (node:child_process:399:12)
    at ChildProcess.emit (node:events:526:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Socket.<anonymous> (node:internal/child_process:451:11)
    at Socket.emit (node:events:526:28)
    at Pipe.<anonymous> (node:net:687:12) {
  killed: false,
  code: 1,
  signal: null,
  cmd: '/Volumes/dev/nativescript/jule_verne/script_tests/node_modules/.bin/node-gyp build --jobs max --release '
}
ERR! install node-gyp failed and return Error Command failed: /Volumes/dev/nativescript/jule_verne/script_tests/node_modules/.bin/node-gyp build --jobs max --release 
ERR! install gyp info it worked if it ends with ok
ERR! install gyp info using node-gyp@8.4.1
ERR! install gyp info using node@16.14.2 | darwin | x64
ERR! install gyp info spawn make
ERR! install gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build', '--jobs', 16 ]
ERR! install In file included from ../cc/core/Size.cc:1:
ERR! install ../cc/core/Size.h:1:10: fatal error: 'opencv2/core.hpp' file not found
ERR! install #include <opencv2/core.hpp>
ERR! install          ^~~~~~~~~~~~~~~~~~
ERR! install In file included from ../cc/core/Rect.cc:1:
ERR! install ../cc/core/Rect.h:1:10: fatal error: 'opencv2/core.hpp' file not found
ERR! install #include <opencv2/core.hpp>
ERR! install          ^~~~~~~~~~~~~~~~~~
ERR! install In file included from ../cc/core/TermCriteria.cc:1:
ERR! install ../cc/core/TermCriteria.h:1:10: fatal error: 'opencv2/core.hpp' file not found
ERR! install #include <opencv2/core.hpp>
ERR! install          ^~~~~~~~~~~~~~~~~~
ERR! install 1 error generated.
ERR! install make: *** [Release/obj.target/opencv4nodejs/cc/core/Size.o] Error 1
ERR! install make: *** Waiting for unfinished jobs....
ERR! install 1 error generated.
ERR! install make: *** [Release/obj.target/opencv4nodejs/cc/core/TermCriteria.o] Error 1
ERR! install 1 error generated.
ERR! install make: *** [Release/obj.target/opencv4nodejs/cc/core/Rect.o] Error 1
ERR! install In file included from ../cc/core/Mat.cc:1:
ERR! install In file included from ../cc/opencv_modules.h:1:
ERR! install ../cc/macros.h:2:10: fatal error: 'opencv2/core.hpp' file not found
ERR! install #include <opencv2/core.hpp>
ERR! install          ^~~~~~~~~~~~~~~~~~
ERR! install In file included from ../cc/core/coreConstants.cc:1:
ERR! install In file included from ../cc/core/coreConstants.h:1:
ERR! install ../cc/macros.h:2:10: fatal error: 'opencv2/core.hpp' file not found
ERR! install #include <opencv2/core.hpp>
ERR! install          ^~~~~~~~~~~~~~~~~~
ERR! install 1 error generated.
ERR! install make: *** [Release/obj.target/opencv4nodejs/cc/core/coreConstants.o] Error 1
ERR! install In file included from ../cc/core/core.cc:1:
ERR! install In file included from ../cc/core/core.h:1:
ERR! install In file included from ../cc/core/Mat.h:1:
ERR! install In file included from ../cc/core/coreUtils.h:1:
ERR! install ../cc/macros.h:2:10: fatal error: 'opencv2/core.hpp' file not found
ERR! install #include <opencv2/core.hpp>
ERR! install          ^~~~~~~~~~~~~~~~~~
ERR! install In file included from ../cc/core/Vec.cc:1:
ERR! install In file included from ../cc/core/Vec.h:1:
ERR! install ../cc/macros.h:2:10: fatal error: 'opencv2/core.hpp' file not found
ERR! install #include <opencv2/core.hpp>
ERR! install          ^~~~~~~~~~~~~~~~~~
ERR! install In file included from ../cc/imgproc/imgprocConstants.cc:1:
ERR! install In file included from ../cc/opencv_modules.h:1:
ERR! install ../cc/macros.h:2:10: fatal error: 'opencv2/core.hpp' file not found
ERR! install #include <opencv2/core.hpp>
ERR! install          ^~~~~~~~~~~~~~~~~~
ERR! install In file included from ../cc/imgproc/imgproc.cc:1:
ERR! install In file included from ../cc/opencv_modules.h:1:
ERR! install ../cc/macros.h:2:10: fatal error: 'opencv2/core.hpp' file not found
ERR! install #include <opencv2/core.hpp>
ERR! install          ^~~~~~~~~~~~~~~~~~
ERR! install In file included from ../cc/core/Point.cc:1:
ERR! install In file included from ../cc/core/Point.h:1:
ERR! install ../cc/macros.h:2:10: fatal error: 'opencv2/core.hpp' file not found
ERR! install #include <opencv2/core.hpp>
ERR! install          ^~~~~~~~~~~~~~~~~~
ERR! install In file included from ../cc/ExternalMemTracking.cc:1:
ERR! install In file included from ../cc/ExternalMemTracking.h:1:
ERR! install ../cc/macros.h:2:10: fatal error: 'opencv2/core.hpp' file not found
ERR! install #include <opencv2/core.hpp>
ERR! install          ^~~~~~~~~~~~~~~~~~
ERR! install 1 error generated.
ERR! install 1 error generated.
ERR! install In file included from ../cc/core/HistAxes.cc:5:
ERR! install In file included from ../cc/core/HistAxes.h:4:
ERR! install ../cc/macros.h:2:10: fatal error: 'opencv2/core.hpp' file not found
ERR! install #include <opencv2/core.hpp>
ERR! install          ^~~~~~~~~~~~~~~~~~
ERR! install In file included from ../cc/core/RotatedRect.cc:1:
ERR! install In file included from ../cc/core/RotatedRect.h:1:
ERR! install ../cc/macros.h:2:10: fatal error: 'opencv2/core.hpp' file not found
ERR! install #include <opencv2/core.hpp>
ERR! install          ^~~~~~~~~~~~~~~~~~
ERR! install 1 error generated.
ERR! install make: *** [Release/obj.target/opencv4nodejs/cc/imgproc/imgprocConstants.o] Error 1
ERR! install make: *** [Release/obj.target/opencv4nodejs/cc/core/HistAxes.o] Error 1
ERR! install 1 error generated.
ERR! install make: *** [Release/obj.target/opencv4nodejs/cc/imgproc/imgproc.o] Error 1
ERR! install In file included from ../cc/imgproc/MatImgproc.cc:1:
ERR! install In file included from ../cc/opencv_modules.h:1:
ERR! install ../cc/macros.h:2:10: fatal error: 'opencv2/core.hpp' file not found
ERR! install #include <opencv2/core.hpp>
ERR! install          ^~~~~~~~~~~~~~~~~~
ERR! install make: *** [Release/obj.target/opencv4nodejs/cc/core/Point.o] Error 1
ERR! install 1 error generated.
ERR! install make: *** [Release/obj.target/opencv4nodejs/cc/imgproc/MatImgproc.o] Error 1
ERR! install 1 error generated.
ERR! install 1 error generated.
ERR! install make: *** [Release/obj.target/opencv4nodejs/cc/core/RotatedRect.o] Error 1
ERR! install make: *** [Release/obj.target/opencv4nodejs/cc/core/Vec.o] Error 1
ERR! install In file included from ../cc/opencv4nodejs.cc:2:
ERR! install In file included from ../cc/ExternalMemTracking.h:1:
ERR! install ../cc/macros.h:2:10: fatal error: 'opencv2/core.hpp' file not found
ERR! install #include <opencv2/core.hpp>
ERR! install          ^~~~~~~~~~~~~~~~~~
ERR! install In file included from ../cc/CustomMatAllocator.cc:1:
ERR! install In file included from ../cc/CustomMatAllocator.h:8:
ERR! install ../cc/core/Size.h:1:10: fatal error: 'opencv2/core.hpp' file not found
ERR! install #include <opencv2/core.hpp>
ERR! install          ^~~~~~~~~~~~~~~~~~
ERR! install 1 error generated.
ERR! install make: *** [Release/obj.target/opencv4nodejs/cc/ExternalMemTracking.o] Error 1
ERR! install 1 error generated.
ERR! install make: *** [Release/obj.target/opencv4nodejs/cc/CustomMatAllocator.o] Error 1
ERR! install 1 error generated.
ERR! install make: *** [Release/obj.target/opencv4nodejs/cc/opencv4nodejs.o] Error 1
ERR! install 1 error generated.
ERR! install make: *** [Release/obj.target/opencv4nodejs/cc/core/core.o] Error 1
ERR! install 1 error generated.
ERR! install make: *** [Release/obj.target/opencv4nodejs/cc/core/Mat.o] Error 1
ERR! install gyp ERR! build error 
ERR! install gyp ERR! stack Error: `make` failed with exit code: 2
ERR! install gyp ERR! stack     at ChildProcess.onExit (/Volumes/dev/nativescript/jule_verne/script_tests/node_modules/node-gyp/lib/build.js:194:23)
ERR! install gyp ERR! stack     at ChildProcess.emit (node:events:526:28)
ERR! install gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
ERR! install gyp ERR! System Darwin 20.6.0
ERR! install gyp ERR! command "/Volumes/data/mguillon/.nvm/versions/node/v16.14.2/bin/node" "/Volumes/dev/nativescript/jule_verne/script_tests/node_modules/.bin/node-gyp" "build" "--jobs" "max" "--release"
ERR! install gyp ERR! cwd /Volumes/dev/nativescript/jule_verne/script_tests/node_modules/@u4/opencv4nodejs
ERR! install gyp ERR! node -v v16.14.2
ERR! install gyp ERR! node-gyp -v v8.4.1
ERR! install gyp ERR! not ok 
ERR! install  return code: 1
```

**Comment by farfromrefug** [comment]
@UrielCh i actually found the issue! it is indeed the fact that the porject build is missing the call to `node-gyp configure`.
And for me it was not working because to call it i need the environment variables to be set before that `node-gyp configure` call.

**Comment by UrielCh** [comment]
rebuild = configure + build
so use rebuid

you can close the issue if it's ok

**Comment by farfromrefug** [comment]
@UrielCh do you mean i can do `build-opencv build` ? 
I think it should be done for me. It is hard to find out what the issue is

**Comment by UrielCh** [comment]
I mean you can call `build-opencv rebuild`

**Comment by farfromrefug** [comment]
@UrielCh OK perfect thanks! that fixes my issue. but should nt the doc  reference that command instead of build? that would prevent users from falling into this issue
