### ISSUE TITLE
Symbol not found: __ZNK2cv12MatAllocator23getBufferPoolControllerEPKc

### ISSUE THREAD

**Issue by fendiflexin** [UrielCh/opencv4nodejs#40]
Installed opencv@4 via brew on mac m1, built via `build-opencv --electron opencv build
`

<--
# Auto Build -Error: dlopen(/Users/riley/Desktop/SquadsElectronClient/SquadsElectronClient/node_modules/@u4/opencv4nodejs/build/Release/opencv4nodejs.node, 1): Symbol not found: __ZNK2cv12MatAllocator23getBufferPoolControllerEPKc
  Referenced from: /Users/riley/Desktop/SquadsElectronClient/SquadsElectronClient/node_modules/@u4/opencv4nodejs/build/Release/opencv4nodejs.node
  Expected in: flat namespace
 in /Users/riley/Desktop/SquadsElectronClient/SquadsElectronClient/node_modules/@u4/opencv4nodejs/build/Release/opencv4nodejs.node
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1800)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1199:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:1800)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at getOpenCV (/Users/riley/Desktop/SquadsElectronClient/SquadsElectronClient/node_modules/@u4/opencv4nodejs/lib/cvloader.js:55:23)
    at loadOpenCV (/Users/riley/Desktop/SquadsElectronClient/SquadsElectronClient/node_modules/@u4/opencv4nodejs/lib/opencv4nodejs.js:9:43)
^C/Users/riley/Desktop/SquadsElectronClient/SquadsElectronClient/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron exited with signal SIGINT -->

*OpenCV version* - 4.5.5

*With OpenCV-contrib?* (extra modules): yes/no? no

*OS*: - mac m1 big sur 11.6.2

**Comment by UrielCh** [comment]
can you provide a sample project?

I have some mac M1 to test, but I do not use electron.

is [opencv-electron](https://github.com/UrielCh/opencv-electron) working ?

**Comment by fendiflexin** [comment]
Yes the opencv-electron is working on my windows x64. However, I successfully built in Mac but it crashes on load. Can you provide a discord? I can share my project.

**Comment by piercus** [comment]
@fendiflexin this is open-source project, if you want free help you need to open the sources of your problem or find a way to reproduce it on open sources !

**Comment by xiatian12345** [comment]
same error,but intel
