### ISSUE TITLE
info config no opencv4nodejs section found in /package.json, is this message supposed to appear?

### ISSUE THREAD

**Issue by IdentifiedBody** [UrielCh/opencv4nodejs#42]
# Problem 

Hello, after some days of trying to install opencv4nodejs I have gotten even further and very close to being able to use it, but whenever I try to run the command node-gyp rebuild it runs into the following problem, I have spent hours looking for a solution but couldn't find anything to solve this

Would appreciate it immensely if anyone could help me out

# Error Message
```
gyp info it worked if it ends with ok
gyp info using node-gyp@9.1.0
gyp info using node@18.6.0 | linux | arm
gyp info find Python using Python version 3.9.2 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/home/pi/.config/nvm/versions/node/v18.6.0/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/pi/Desktop/opencvTest/node_modules/@u4/opencv4nodejs/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/pi/.config/nvm/versions/node/v18.6.0/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/pi/.cache/node-gyp/18.6.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/pi/.cache/node-gyp/18.6.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/pi/.config/nvm/versions/node/v18.6.0/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/pi/.cache/node-gyp/18.6.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/pi/Desktop/opencvTest/node_modules/@u4/opencv4nodejs',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/pi/Desktop/opencvTest/node_modules/@u4/opencv4nodejs/build'
  CXX(target) Release/obj.target/opencv4nodejs/cc/opencv4nodejs.o
In file included from ../cc/ExternalMemTracking.h:1,
                 from ../cc/opencv4nodejs.cc:2:
../cc/macros.h:2:10: fatal error: opencv2/core.hpp: No such file or directory
    2 | #include <opencv2/core.hpp>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [opencv4nodejs.target.mk:216: Release/obj.target/opencv4nodejs/cc/opencv4nodejs.o] Error 1
make: Leaving directory '/home/pi/Desktop/opencvTest/node_modules/@u4/opencv4nodejs/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/pi/.config/nvm/versions/node/v18.6.0/lib/node_modules/node-gyp/lib/build.js:201:23)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Linux 5.15.32-v7+
gyp ERR! command "/home/pi/.config/nvm/versions/node/v18.6.0/bin/node" "/home/pi/.config/nvm/versions/node/v18.6.0/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/pi/Desktop/opencvTest/node_modules/@u4/opencv4nodejs
gyp ERR! node -v v18.6.0
gyp ERR! node-gyp -v v9.1.0
gyp ERR! not ok 

<!--

If you are facing issues installing opencv4nodejs, please scroll through the terminal output of the build script and find the error message, causing the build to fail. Copy and paste the error message from your terminal into this section.

IMPORTANT! The following error summary messages do not help, please do not upload them here!

error code ELIFECYCLE
error errno 1
error <pkg> install: `node ./install.js`
error Exit status 1
error Failed at the <pkg> install script.
error This is probably not a problem with npm. There is likely additional logging output above.
verbose exit [ 1, true ]

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! <pkg> install: node-gyp rebuild
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the <pkg> install script.
npm ERR! This is probably not a problem with npm. There is likely additional `log`
```

-->

*OpenCV version*: 4.5.5

*OS*: Debian

**Comment by UrielCh** [comment]
`node-gyp rebuild` must no be called directly.
opencv4nodejs contains it's own node-gyp launcher, check the doc,

**Comment by IdentifiedBody** [comment]
I thought that i needed to run "node-gyp rebuild" to fix the  error with the "npm run install_4.5.5_cuda" command (after already having been done with the build returns this log)



```
opencvtest@1.0.0 install_4.5.5_cuda
> build-opencv --version 4.5.5 --flags="-DWITH_CUDA=ON -DWITH_CUDNN=ON -DOPENCV_DNN_CUDA=OFF -DCUDA_FAST_MATH=ON" build

info config no opencv4nodejs section found in /home/pi/Desktop/opencvTest/package.json
info init using openCV verison 4.5.5
info init INIT_CWD is defined overwriting root path to /home/pi/Desktop/opencvTest
info init Workdir will be: /home/pi/Desktop/opencvTest/node_modules/@u4/opencv-build/opencv-4.5.5-90361
info install Using openCV 4.5.5
info install Using lib dir: /home/pi/Desktop/opencvTest/node_modules/@u4/opencv-build/opencv-4.5.5-90361/build/lib
info install if you want to use an own OpenCV build set OPENCV4NODEJS_DISABLE_AUTOBUILD to 1, and fill OPENCV_BIN_DIR, OPENCV_INCLUDE_DIR, OPENCV_LIB_DIR environement variables
info install found previous build summery auto-build.json: /home/pi/Desktop/opencvTest/node_modules/@u4/opencv-build/opencv-4.5.5-90361/auto-build.json
info install checking for opencv libraries
info install lib calib3d: /home/pi/Desktop/opencvTest/node_modules/@u4/opencv-build/opencv-4.5.5-90361/build/lib/libopencv_calib3d.so.4.5.5
info install lib core: /home/pi/Desktop/opencvTest/node_modules/@u4/opencv-build/opencv-4.5.5-90361/build/lib/libopencv_core.so.4.5.5
info install lib dnn: /home/pi/Desktop/opencvTest/node_modules/@u4/opencv-build/opencv-4.5.5-90361/build/lib/libopencv_dnn.so.4.5.5
info install lib features2d: /home/pi/Desktop/opencvTest/node_modules/@u4/opencv-build/opencv-4.5.5-90361/build/lib/libopencv_features2d.so.4.5.5
info install lib flann: /home/pi/Desktop/opencvTest/node_modules/@u4/opencv-build/opencv-4.5.5-90361/build/lib/libopencv_flann.so.4.5.5
info install lib gapi: /home/pi/Desktop/opencvTest/node_modules/@u4/opencv-build/opencv-4.5.5-90361/build/lib/libopencv_gapi.so.4.5.5
info install lib highgui: /home/pi/Desktop/opencvTest/node_modules/@u4/opencv-build/opencv-4.5.5-90361/build/lib/libopencv_highgui.so.4.5.5
info install lib imgcodecs: /home/pi/Desktop/opencvTest/node_modules/@u4/opencv-build/opencv-4.5.5-90361/build/lib/libopencv_imgcodecs.so.4.5.5
info install lib imgproc: /home/pi/Desktop/opencvTest/node_modules/@u4/opencv-build/opencv-4.5.5-90361/build/lib/libopencv_imgproc.so.4.5.5
info install lib ml: /home/pi/Desktop/opencvTest/node_modules/@u4/opencv-build/opencv-4.5.5-90361/build/lib/libopencv_ml.so.4.5.5
info install lib objdetect: /home/pi/Desktop/opencvTest/node_modules/@u4/opencv-build/opencv-4.5.5-90361/build/lib/libopencv_objdetect.so.4.5.5
info install lib photo: /home/pi/Desktop/opencvTest/node_modules/@u4/opencv-build/opencv-4.5.5-90361/build/lib/libopencv_photo.so.4.5.5
info install python_tests: ignored
info install lib video: /home/pi/Desktop/opencvTest/node_modules/@u4/opencv-build/opencv-4.5.5-90361/build/lib/libopencv_video.so.4.5.5
info install lib videoio: /home/pi/Desktop/opencvTest/node_modules/@u4/opencv-build/opencv-4.5.5-90361/build/lib/libopencv_videoio.so.4.5.5
info install lib videostab: /home/pi/Desktop/opencvTest/node_modules/@u4/opencv-build/opencv-4.5.5-90361/build/lib/libopencv_videostab.so.4.5.5
info install lib face: /home/pi/Desktop/opencvTest/node_modules/@u4/opencv-build/opencv-4.5.5-90361/build/lib/libopencv_face.so.4.5.5
info install lib text: /home/pi/Desktop/opencvTest/node_modules/@u4/opencv-build/opencv-4.5.5-90361/build/lib/libopencv_text.so.4.5.5
info install lib tracking: /home/pi/Desktop/opencvTest/node_modules/@u4/opencv-build/opencv-4.5.5-90361/build/lib/libopencv_tracking.so.4.5.5
info install lib xfeatures2d: /home/pi/Desktop/opencvTest/node_modules/@u4/opencv-build/opencv-4.5.5-90361/build/lib/libopencv_xfeatures2d.so.4.5.5
info install lib ximgproc: /home/pi/Desktop/opencvTest/node_modules/@u4/opencv-build/opencv-4.5.5-90361/build/lib/libopencv_ximgproc.so.4.5.5
info install all libraries are installed in /home/pi/Desktop/opencvTest/node_modules/@u4/opencv-build/opencv-4.5.5-90361/build/lib => Skip building
info install 
info install Found the following libs:
info install calib3d: /home/pi/Desktop/opencvTest/node_modules/@u4/opencv-build/opencv-4.5.5-90361/build/lib/libopencv_calib3d.so.4.5.5
info install core: /home/pi/Desktop/opencvTest/node_modules/@u4/opencv-build/opencv-4.5.5-90361/build/lib/libopencv_core.so.4.5.5
info install dnn: /home/pi/Desktop/opencvTest/node_modules/@u4/opencv-build/opencv-4.5.5-90361/build/lib/libopencv_dnn.so.4.5.5
info install features2d: /home/pi/Desktop/opencvTest/node_modules/@u4/opencv-build/opencv-4.5.5-90361/build/lib/libopencv_features2d.so.4.5.5
info install flann: /home/pi/Desktop/opencvTest/node_modules/@u4/opencv-build/opencv-4.5.5-90361/build/lib/libopencv_flann.so.4.5.5
info install gapi: /home/pi/Desktop/opencvTest/node_modules/@u4/opencv-build/opencv-4.5.5-90361/build/lib/libopencv_gapi.so.4.5.5
info install highgui: /home/pi/Desktop/opencvTest/node_modules/@u4/opencv-build/opencv-4.5.5-90361/build/lib/libopencv_highgui.so.4.5.5
info install imgcodecs: /home/pi/Desktop/opencvTest/node_modules/@u4/opencv-build/opencv-4.5.5-90361/build/lib/libopencv_imgcodecs.so.4.5.5
info install imgproc: /home/pi/Desktop/opencvTest/node_modules/@u4/opencv-build/opencv-4.5.5-90361/build/lib/libopencv_imgproc.so.4.5.5
info install ml: /home/pi/Desktop/opencvTest/node_modules/@u4/opencv-build/opencv-4.5.5-90361/build/lib/libopencv_ml.so.4.5.5
info install objdetect: /home/pi/Desktop/opencvTest/node_modules/@u4/opencv-build/opencv-4.5.5-90361/build/lib/libopencv_objdetect.so.4.5.5
info install photo: /home/pi/Desktop/opencvTest/node_modules/@u4/opencv-build/opencv-4.5.5-90361/build/lib/libopencv_photo.so.4.5.5
info install video: /home/pi/Desktop/opencvTest/node_modules/@u4/opencv-build/opencv-4.5.5-90361/build/lib/libopencv_video.so.4.5.5
info install videoio: /home/pi/Desktop/opencvTest/node_modules/@u4/opencv-build/opencv-4.5.5-90361/build/lib/libopencv_videoio.so.4.5.5
info install videostab: /home/pi/Desktop/opencvTest/node_modules/@u4/opencv-build/opencv-4.5.5-90361/build/lib/libopencv_videostab.so.4.5.5
info install face: /home/pi/Desktop/opencvTest/node_modules/@u4/opencv-build/opencv-4.5.5-90361/build/lib/libopencv_face.so.4.5.5
info install text: /home/pi/Desktop/opencvTest/node_modules/@u4/opencv-build/opencv-4.5.5-90361/build/lib/libopencv_text.so.4.5.5
info install tracking: /home/pi/Desktop/opencvTest/node_modules/@u4/opencv-build/opencv-4.5.5-90361/build/lib/libopencv_tracking.so.4.5.5
info install xfeatures2d: /home/pi/Desktop/opencvTest/node_modules/@u4/opencv-build/opencv-4.5.5-90361/build/lib/libopencv_xfeatures2d.so.4.5.5
info install ximgproc: /home/pi/Desktop/opencvTest/node_modules/@u4/opencv-build/opencv-4.5.5-90361/build/lib/libopencv_ximgproc.so.4.5.5
info defines 
info defines Setting the following defines:
info defines OPENCV4NODEJS_FOUND_LIBRARY_CALIB3D     OPENCV4NODEJS_FOUND_LIBRARY_CORE        OPENCV4NODEJS_FOUND_LIBRARY_DNN         
info defines OPENCV4NODEJS_FOUND_LIBRARY_FEATURES2D  OPENCV4NODEJS_FOUND_LIBRARY_FLANN       OPENCV4NODEJS_FOUND_LIBRARY_GAPI        
info defines OPENCV4NODEJS_FOUND_LIBRARY_HIGHGUI     OPENCV4NODEJS_FOUND_LIBRARY_IMGCODECS   OPENCV4NODEJS_FOUND_LIBRARY_IMGPROC     
info defines OPENCV4NODEJS_FOUND_LIBRARY_ML          OPENCV4NODEJS_FOUND_LIBRARY_OBJDETECT   OPENCV4NODEJS_FOUND_LIBRARY_PHOTO       
info defines OPENCV4NODEJS_FOUND_LIBRARY_VIDEO       OPENCV4NODEJS_FOUND_LIBRARY_VIDEOIO     OPENCV4NODEJS_FOUND_LIBRARY_VIDEOSTAB   
info defines OPENCV4NODEJS_FOUND_LIBRARY_FACE        OPENCV4NODEJS_FOUND_LIBRARY_TEXT        OPENCV4NODEJS_FOUND_LIBRARY_TRACKING    
info defines OPENCV4NODEJS_FOUND_LIBRARY_XFEATURES2D OPENCV4NODEJS_FOUND_LIBRARY_XIMGPROC    
info install 
info install Setting the following includes:
info includes /home/pi/Desktop/opencvTest/node_modules/@u4/opencv-build/opencv-4.5.5-90361/build/include
info includes /home/pi/Desktop/opencvTest/node_modules/@u4/opencv-build/opencv-4.5.5-90361/build/include/opencv4
info libs 
info libs Setting lib from -L/home/pi/Desktop/opencvTest/node_modules/@u4/opencv-build/opencv-4.5.5-90361/build : lib, -lopencv_calib3d, -lopencv_core, -lopencv_dnn, -lopencv_features2d, -lopencv_flann, -lopencv_gapi, -lopencv_highgui, -lopencv_imgcodecs, -lopencv_imgproc, -lopencv_ml, -lopencv_objdetect, -lopencv_photo, -lopencv_video, -lopencv_videoio, -lopencv_videostab, -lopencv_face, -lopencv_text, -lopencv_tracking, -lopencv_xfeatures2d, -lopencv_ximgproc, lib
info install Spawning in directory:/home/pi/Desktop/opencvTest/node_modules/@u4/opencv4nodejs node-gyp process: node-gyp build --jobs max --release 
gyp info it worked if it ends with ok
gyp info using node-gyp@9.1.0
gyp info using node@18.6.0 | linux | arm
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build', '--jobs', 4 ]
make: Entering directory '/home/pi/Desktop/opencvTest/node_modules/@u4/opencv4nodejs/build'
  CXX(target) Release/obj.target/opencv4nodejs/cc/opencv4nodejs.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/CustomMatAllocator.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/ExternalMemTracking.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/core/core.o
In file included from ../cc/ExternalMemTracking.h:1,
                 from ../cc/opencv4nodejs.cc:2:
../cc/macros.h:2:10: fatal error: opencv2/core.hpp: No such file or directory
    2 | #include <opencv2/core.hpp>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from ../cc/CustomMatAllocator.h:8,
                 from ../cc/CustomMatAllocator.cc:1:
../cc/core/Size.h:1:10: fatal error: opencv2/core.hpp: No such file or directory
    1 | #include <opencv2/core.hpp>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from ../cc/ExternalMemTracking.h:1,
                 from ../cc/ExternalMemTracking.cc:1:
../cc/macros.h:2:10: fatal error: opencv2/core.hpp: No such file or directory
    2 | #include <opencv2/core.hpp>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [opencv4nodejs.target.mk:216: Release/obj.target/opencv4nodejs/cc/CustomMatAllocator.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [opencv4nodejs.target.mk:216: Release/obj.target/opencv4nodejs/cc/opencv4nodejs.o] Error 1
In file included from ../cc/core/coreUtils.h:1,
                 from ../cc/core/Mat.h:1,
                 from ../cc/core/core.h:1,
                 from ../cc/core/core.cc:1:
../cc/macros.h:2:10: fatal error: opencv2/core.hpp: No such file or directory
    2 | #include <opencv2/core.hpp>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [opencv4nodejs.target.mk:216: Release/obj.target/opencv4nodejs/cc/ExternalMemTracking.o] Error 1
make: *** [opencv4nodejs.target.mk:216: Release/obj.target/opencv4nodejs/cc/core/core.o] Error 1
make: Leaving directory '/home/pi/Desktop/opencvTest/node_modules/@u4/opencv4nodejs/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/pi/Desktop/opencvTest/node_modules/node-gyp/lib/build.js:201:23)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Linux 5.15.32-v7+
gyp ERR! command "/home/pi/.config/nvm/versions/node/v18.6.0/bin/node" "/home/pi/Desktop/opencvTest/node_modules/.bin/node-gyp" "build" "--jobs" "max" "--release"
gyp ERR! cwd /home/pi/Desktop/opencvTest/node_modules/@u4/opencv4nodejs
gyp ERR! node -v v18.6.0
gyp ERR! node-gyp -v v9.1.0
gyp ERR! not ok 
error:  Error: Command failed: node-gyp build --jobs max --release 
gyp info it worked if it ends with ok
gyp info using node-gyp@9.1.0
gyp info using node@18.6.0 | linux | arm
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build', '--jobs', 4 ]
In file included from ../cc/ExternalMemTracking.h:1,
                 from ../cc/opencv4nodejs.cc:2:
../cc/macros.h:2:10: fatal error: opencv2/core.hpp: No such file or directory
    2 | #include <opencv2/core.hpp>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from ../cc/CustomMatAllocator.h:8,
                 from ../cc/CustomMatAllocator.cc:1:
../cc/core/Size.h:1:10: fatal error: opencv2/core.hpp: No such file or directory
    1 | #include <opencv2/core.hpp>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from ../cc/ExternalMemTracking.h:1,
                 from ../cc/ExternalMemTracking.cc:1:
../cc/macros.h:2:10: fatal error: opencv2/core.hpp: No such file or directory
    2 | #include <opencv2/core.hpp>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [opencv4nodejs.target.mk:216: Release/obj.target/opencv4nodejs/cc/CustomMatAllocator.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [opencv4nodejs.target.mk:216: Release/obj.target/opencv4nodejs/cc/opencv4nodejs.o] Error 1
In file included from ../cc/core/coreUtils.h:1,
                 from ../cc/core/Mat.h:1,
                 from ../cc/core/core.h:1,
                 from ../cc/core/core.cc:1:
../cc/macros.h:2:10: fatal error: opencv2/core.hpp: No such file or directory
    2 | #include <opencv2/core.hpp>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [opencv4nodejs.target.mk:216: Release/obj.target/opencv4nodejs/cc/ExternalMemTracking.o] Error 1
make: *** [opencv4nodejs.target.mk:216: Release/obj.target/opencv4nodejs/cc/core/core.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/pi/Desktop/opencvTest/node_modules/node-gyp/lib/build.js:201:23)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Linux 5.15.32-v7+
gyp ERR! command "/home/pi/.config/nvm/versions/node/v18.6.0/bin/node" "/home/pi/Desktop/opencvTest/node_modules/.bin/node-gyp" "build" "--jobs" "max" "--release"
gyp ERR! cwd /home/pi/Desktop/opencvTest/node_modules/@u4/opencv4nodejs
gyp ERR! node -v v18.6.0
gyp ERR! node-gyp -v v9.1.0
gyp ERR! not ok 

    at ChildProcess.exithandler (node:child_process:389:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'node-gyp build --jobs max --release '
}
ERR! install node-gyp failed and return Error Command failed: node-gyp build --jobs max --release 
ERR! install gyp info it worked if it ends with ok
ERR! install gyp info using node-gyp@9.1.0
ERR! install gyp info using node@18.6.0 | linux | arm
ERR! install gyp info spawn make
ERR! install gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build', '--jobs', 4 ]
ERR! install In file included from ../cc/ExternalMemTracking.h:1,
ERR! install                  from ../cc/opencv4nodejs.cc:2:
ERR! install ../cc/macros.h:2:10: fatal error: opencv2/core.hpp: No such file or directory
ERR! install     2 | #include <opencv2/core.hpp>
ERR! install       |          ^~~~~~~~~~~~~~~~~~
ERR! install compilation terminated.
ERR! install In file included from ../cc/CustomMatAllocator.h:8,
ERR! install                  from ../cc/CustomMatAllocator.cc:1:
ERR! install ../cc/core/Size.h:1:10: fatal error: opencv2/core.hpp: No such file or directory
ERR! install     1 | #include <opencv2/core.hpp>
ERR! install       |          ^~~~~~~~~~~~~~~~~~
ERR! install compilation terminated.
ERR! install In file included from ../cc/ExternalMemTracking.h:1,
ERR! install                  from ../cc/ExternalMemTracking.cc:1:
ERR! install ../cc/macros.h:2:10: fatal error: opencv2/core.hpp: No such file or directory
ERR! install     2 | #include <opencv2/core.hpp>
ERR! install       |          ^~~~~~~~~~~~~~~~~~
ERR! install compilation terminated.
ERR! install make: *** [opencv4nodejs.target.mk:216: Release/obj.target/opencv4nodejs/cc/CustomMatAllocator.o] Error 1
ERR! install make: *** Waiting for unfinished jobs....
ERR! install make: *** [opencv4nodejs.target.mk:216: Release/obj.target/opencv4nodejs/cc/opencv4nodejs.o] Error 1
ERR! install In file included from ../cc/core/coreUtils.h:1,
ERR! install                  from ../cc/core/Mat.h:1,
ERR! install                  from ../cc/core/core.h:1,
ERR! install                  from ../cc/core/core.cc:1:
ERR! install ../cc/macros.h:2:10: fatal error: opencv2/core.hpp: No such file or directory
ERR! install     2 | #include <opencv2/core.hpp>
ERR! install       |          ^~~~~~~~~~~~~~~~~~
ERR! install compilation terminated.
ERR! install make: *** [opencv4nodejs.target.mk:216: Release/obj.target/opencv4nodejs/cc/ExternalMemTracking.o] Error 1
ERR! install make: *** [opencv4nodejs.target.mk:216: Release/obj.target/opencv4nodejs/cc/core/core.o] Error 1
ERR! install gyp ERR! build error 
ERR! install gyp ERR! stack Error: `make` failed with exit code: 2
ERR! install gyp ERR! stack     at ChildProcess.onExit (/home/pi/Desktop/opencvTest/node_modules/node-gyp/lib/build.js:201:23)
ERR! install gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
ERR! install gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
ERR! install gyp ERR! System Linux 5.15.32-v7+
ERR! install gyp ERR! command "/home/pi/.config/nvm/versions/node/v18.6.0/bin/node" "/home/pi/Desktop/opencvTest/node_modules/.bin/node-gyp" "build" "--jobs" "max" "--release"
ERR! install gyp ERR! cwd /home/pi/Desktop/opencvTest/node_modules/@u4/opencv4nodejs
ERR! install gyp ERR! node -v v18.6.0
ERR! install gyp ERR! node-gyp -v v9.1.0
ERR! install gyp ERR! not ok 
ERR! install  return code: 1

```

**Comment by IdentifiedBody** [comment]
i have finished an auto build installation and reach the end successfully, but whenever i try to "node index.js" it gives me this ```
error 
node index.js 
info config no opencv4nodejs section found in /home/pi/Documents/anothertryNPM/package.json

```

**Comment by UrielCh** [comment]
That an info not an error.

**Comment by IdentifiedBody** [comment]
How can i use this info to get the package working? I try calling `const cv = require('@u4/opencv4nodejs')`
but then i can't use it due to that info im guessing.

**Comment by UrielCh** [comment]
provide a code if you want help not a simple require line

**Comment by UrielCh** [comment]
> info config no opencv4nodejs section found in /package.json, is this message supposed to appear?
the short answer is YES.
