### ISSUE TITLE
dlopen(.../node_modules/@u4/opencv4nodejs/build/Release/opencv4nodejs.node, 0x0001): symbol not found in flat namespace... 

### ISSUE THREAD

**Issue by cbhh** [UrielCh/opencv4nodejs#74]
# Error Message

Error: dlopen(/Users/littlemeteor/Documents/opencv4nodejs-test/node_modules/@u4/opencv4nodejs/build/Release/opencv4nodejs.node, 0x0001): symbol not found in flat namespace '__ZNK2cv12MatAllocator23getBufferPoolControllerEPKc'
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1249:18)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1067:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at getOpenCV (/Users/littlemeteor/Documents/opencv4nodejs-test/node_modules/@u4/opencv4nodejs/lib/cvloader.js:54:23)
    at loadOpenCV (/Users/littlemeteor/Documents/opencv4nodejs-test/node_modules/@u4/opencv4nodejs/lib/opencv4nodejs.js:6:48)
    at Object.<anonymous> (/Users/littlemeteor/Documents/opencv4nodejs-test/node_modules/@u4/opencv4nodejs/lib/opencv4nodejs.js:21:12)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10) {
  code: 'ERR_DLOPEN_FAILED'
}

# Auto Build - Full Error Log

# Manual Build - Environment Information

I installed the opencv with homebrew, then run `install_arm64` script in `package.json` to build opencv4nodejs
the tools I used are: 
- nodejs@16.19
- node-gyp@9.3.1
- python@3.11.2

node-gyp has successfully built opencv4nodejs.node, but when I run `require("@u4/opencv4nodejs")` in `test.js`(a minimize test environment, only has this line of code), errors printed above occured: symbol not found in flat namespace....
my test code is here: [https://github.com/cbhh/opencv4nodejs-test](https://github.com/cbhh/opencv4nodejs-test)
I also uploaded build output files `Release.zip` to the repository

*OpenCV version*: 4.7.0_1

*With OpenCV-contrib?* (extra modules): yes

*OS*: macOS 13.2 on Apple M1

**Comment by UrielCh** [comment]
You can now try the new version V6.4.4

I think that your setup failed due to a missing Typescript dependence. (removed in v6.4.4)

**Comment by xiongzhend** [comment]
yes, I almost have the same issue here, I installed opencv@4.7.0_2, and opencv4nodejs, and run opencv-build, finally got this issue, I think it is due to my node version should be v12, not v16

nodejs@16.19
node-gyp@9.3.1
python@3.11.2

**Comment by petem24** [comment]
any fix for this?
