### ISSUE TITLE
OPENCV_LIB_DIR environment variables doesn't work

### ISSUE THREAD

**Issue by Shin-Ogata** [UrielCh/opencv4nodejs#8]
I'm sorry in a row.
It looks like the `OPENCV_LIB_DIR` specification isn't working.

I have built and installed OpenCV on my Linux system in advance, and set environment variables as follows.
```sh
export OPENCV4NODEJS_DISABLE_AUTOBUILD=1
export OPENCV_INCLUDE_DIR="/usr/local/include/opencv4"
export OPENCV_LIB_DIR="/usr/local/lib"
export OPENCV_BIN_DIR="/usr/local/bin"
```

# Error Message
```
/home/user/check-opencv/node_modules/@u4/opencv-build/lib/getLibsFactory.js:78
            throw new Error(`specified lib dir does not exist: ${libDir}`);
                  ^

Error: specified lib dir does not exist: /home/user/check-opencv/node_modules/@u4/opencv-build/opencv-4.5.4-8189d/build/lib
    at getLibsFactory.getLibs (/home/user/check-opencv/node_modules/@u4/opencv-build/lib/getLibsFactory.js:78:19)
    at SetupOpencv.writeAutoBuildFile (/home/user/check-opencv/node_modules/@u4/opencv-build/lib/setupOpencv.js:112:43)
    at OpenCVBuilder.writeAutoBuildFile (/home/user/check-opencv/node_modules/@u4/opencv-build/lib/OpenCVBuilder.js:76:48)
    at Object.compileLib (/home/user/check-opencv/node_modules/@u4/opencv4nodejs/install/compileLib.js:155:17)
    at Object.<anonymous> (/home/user/check-opencv/node_modules/@u4/opencv4nodejs/bin/install.js:4:12)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)

```

# Work arround

This is caused the `env.opencvLibDir` variable is not rewritten.
https://github.com/UrielCh/npm-opencv-build/blob/master/src/getLibsFactory.ts#L80

I can fix it as follows and it worked, but I don't know how to fix it correctly.

- [opencv4nodejs/install/compileLib.ts#L43-L45](https://github.com/UrielCh/opencv4nodejs/blob/master/install/compileLib.ts#L43-L45)
```ts
function getLibDir(env) {
    if (env.isAutoBuildDisabled) {
        const dir = resolvePath(process.env.OPENCV_LIB_DIR) || getDefaultLibDir(env);
        {// ★ HACK
            // mkdir for `auto-build.json`
            if (!fs.existsSync(env.opencvLibDir)) {
                fs.mkdirSync(env.opencvLibDir, { recursive: true });
            }
            // force overwrite
            Reflect.defineProperty(env, 'opencvLibDir', {value: dir})
        }
        return dir;
    }
    :
}
```

- [opencv4nodejs/install/compileLib.ts#L152-L154](https://github.com/UrielCh/opencv4nodejs/blob/master/install/compileLib.ts#L152-L154)
```ts
    if (!fs.existsSync(libDir)) {
        await builder.install();
    } else {
        // ★ HACK
        builder.writeAutoBuildFile();
    }

```

- [npm-opencv-build/src/OpenCVBuilder.ts#L61](https://github.com/UrielCh/npm-opencv-build/blob/master/src/OpenCVBuilder.ts#L61)
```ts
    writeAutoBuildFile() {
        new SetupOpencv(this).writeAutoBuildFile();
    }
```

So, the reason for calling writeAutoBuildFile () is that it will fail to start unless you create `auto-build.json`.

Best, regards.

*OpenCV version* (example 3.4.1): 4.5.4

*With OpenCV-contrib?* (extra modules): no

*OS*: Linux Ubuntu 18.4 (on WSL2)

**Comment by UrielCh** [comment]
I made a lot's of build tests with this package,

Can you try not to use OPENCV4NODEJS_DISABLE_AUTOBUILD, for now, I'm only focusing, on the local build version?

**Comment by Shin-Ogata** [comment]
> Can you try not to use OPENCV4NODEJS_DISABLE_AUTOBUILD, for now, I'm only focusing, on the local build version?

I tried it without OPENCV4NODEJS_DISABLE_AUTOBUILD, but it started downloading and building of the default `v4.5.4`.
First I tried it against to the local `v4.5.5` and then tried against to the `v3.4.14`, but the result was the same.

- console log
```
info config no opencv4nodejs section found in /home/user/check-opencv/package.json
info init no openCV version given using default verison 4.5.4
info init INIT_CWD is defined overwriting root path to  /home/user/check-opencv
info init Workdir will be: /home/user/check-opencv/node_modules/@u4/opencv-build/opencv-4.5.4
info install Using openCV 4.5.4
info install Using lib dir: /home/user/check-opencv/node_modules/@u4/opencv-build/opencv-4.5.4/build/lib
info install if you want to use an own OpenCV installation set OPENCV4NODEJS_DISABLE_AUTOBUILD
info readAutoBuildFile file does not exists: /home/user/check-opencv/node_modules/@u4/opencv-build/opencv-4.5.4/auto-build.json
info install 
info install running install script...
info install 
info install opencv version: 4.5.4
info install with opencv contrib: yes
info install custom build flags: < none >
info install 
info install executing: git --version
info install git Version 2.17.1 found
info install executing: cmake --version
info install cmake Version 3.20.2 found
info install installing opencv version 4.5.4 into directory: /home/user/check-opencv/node_modules/@u4/opencv-build/opencv-4.5.4
info install Cleaning old build, src, contrib-src directories
info install git clone https://github.com/opencv/opencv_contrib.git
remote: Enumerating objects: 3740, done.
:

```

And next, I also tried using the `opencv4nodejs` section in `package.json` and the result was still the same.

- pacakge.json
```json
  "dependencies": {
    "@u4/opencv4nodejs": "^6.0.10"
  },
  "opencv4nodejs": {
    "autoBuildFlags": "-DCMAKE_BUILD_RPATH=$ORIGIN",
    "autoBuildWithoutContrib": true,
    "opencvIncludeDir": "/usr/local/include",
    "opencvLibDir": "/usr/local/lib",
    "opencvBinDir": "/usr/local/bin"
  },
  "keywords": [],

```

- console log
```
info config found opencv4nodejs section in /home/user/check-opencv/package.json
info init no openCV version given using default verison 4.5.4
info init INIT_CWD is defined overwriting root path to  /home/user/check-opencv
info applyEnvsFromPackageJson the following opencv4nodejs environment variables are set in the package.json:
info applyEnvsFromPackageJson win:autoBuildFlags: -DCMAKE_BUILD_RPATH=$ORIGIN,-DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded$<$<CONFIG:Debug>:Debug>
info applyEnvsFromPackageJson autoBuildFlags: -DCMAKE_BUILD_RPATH=$ORIGIN
info applyEnvsFromPackageJson autoBuildWithoutContrib: true
info applyEnvsFromPackageJson opencvIncludeDir: /usr/local/include
info applyEnvsFromPackageJson opencvLibDir: /usr/local/lib
info applyEnvsFromPackageJson opencvBinDir: /usr/local/bin
info init Workdir will be: /home/user/check-opencv/node_modules/@u4/opencv-build/opencv-4.5.4-8189d
info install Using openCV 4.5.4
info install Using lib dir: /home/user/check-opencv/node_modules/@u4/opencv-build/opencv-4.5.4-8189d/build/lib
info install if you want to use an own OpenCV installation set OPENCV4NODEJS_DISABLE_AUTOBUILD
info readAutoBuildFile file does not exists: /home/user/check-opencv/node_modules/@u4/opencv-build/opencv-4.5.4-8189d/auto-build.json
info install 
info install running install script...
info install 
info install opencv version: 4.5.4
info install with opencv contrib: no
info install custom build flags: -DCMAKE_BUILD_RPATH=$ORIGIN
info install 
info install executing: git --version
info install git Version 2.17.1 found
info install executing: cmake --version
info install cmake Version 3.20.2 found
info install installing opencv version 4.5.4 into directory: /home/user/check-opencv/node_modules/@u4/opencv-build/opencv-4.5.4-8189d
info install Cleaning old build, src, contrib-src directories
info install skipping download of opencv_contrib since OPENCV4NODEJS_AUTOBUILD_WITHOUT_CONTRIB is set
info install git clone https://github.com/opencv/opencv.git
remote: Enumerating objects: 8260, done.
:
```

**Comment by UrielCh** [comment]
can you send me the end of your first build attempt?
the part with the error message.

and please unset your INIT_CWD variable. I'm not sure it works
see doc:
```
   --root <value>       OpenCV-build root directory (deprecated) (INIT_CWD env variable)
```

use OPENCV_BUILD_ROOT instead.

**Comment by Shin-Ogata** [comment]
> can you send me the end of your first build attempt?
> the part with the error message.

There is no error.
Because it just ignores OPENCV_LIB_DIR and does the default behavior.

<details>
<summary>No eror log</summary>

```
info install Spawning in directory:/home/ogata/work/fs/npm-test/check-opencv/node_modules/@u4/opencv4nodejs node-gyp process: node-gyp rebuild --jobs max
gyp info it worked if it ends with ok
gyp info using node-gyp@8.3.0
gyp info using node@16.13.1 | linux | x64
gyp info find Python using Python version 3.6.9 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/home/ogata/.nvm/versions/node/v16.13.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ogata/work/fs/npm-test/check-opencv/node_modules/@u4/opencv4nodejs/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ogata/.nvm/versions/node/v16.13.1/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ogata/.cache/node-gyp/16.13.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/ogata/.cache/node-gyp/16.13.1',
gyp info spawn args   '-Dnode_gyp_dir=/home/ogata/.nvm/versions/node/v16.13.1/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/ogata/.cache/node-gyp/16.13.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/ogata/work/fs/npm-test/check-opencv/node_modules/@u4/opencv4nodejs',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build', '--jobs', 12 ]
make: Entering directory '/home/ogata/work/fs/npm-test/check-opencv/node_modules/@u4/opencv4nodejs/build'
  CXX(target) Release/obj.target/opencv4nodejs/cc/opencv4nodejs.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/CustomMatAllocator.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/ExternalMemTracking.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/core/core.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/core/coreConstants.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/core/HistAxes.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/core/Mat.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/core/Point.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/core/Vec.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/core/Size.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/core/Rect.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/core/RotatedRect.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/core/TermCriteria.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/imgproc/imgproc.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/imgproc/imgprocConstants.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/imgproc/MatImgproc.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/imgproc/Contour.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/imgproc/Moments.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/calib3d/calib3d.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/calib3d/calib3dConstants.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/calib3d/MatCalib3d.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/io/io.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/io/ioConstants.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/io/VideoCapture.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/io/VideoWriter.o
In file included from /home/ogata/work/fs/npm-test/check-opencv/node_modules/@u4/opencv-build/opencv-4.5.4/build/include/opencv4/opencv2/ml.hpp:1951:0,
                 from ../cc/machinelearning/machinelearning.h:3,
                 from ../cc/opencv4nodejs.cc:29:
/home/ogata/work/fs/npm-test/check-opencv/node_modules/@u4/opencv-build/opencv-4.5.4/build/include/opencv4/opencv2/ml/ml.inl.hpp: In function ‘int cv::ml::simulatedAnnealingSolver(SimulatedAnnealingSolverSystem&, double, double, double, size_t, double*, cv::RNG&)’:
/home/ogata/work/fs/npm-test/check-opencv/node_modules/@u4/opencv-build/opencv-4.5.4/build/include/opencv4/opencv2/ml/ml.inl.hpp:55:0: note: -Wmisleading-indentation is disabled from this point onwards, since column-tracking was disabled due to the size of the code/headers
     return exchange;
 
  CXX(target) Release/obj.target/opencv4nodejs/cc/photo/photo.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/photo/photoConstants.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/photo/MatPhoto.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/video/video.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/video/BackgroundSubtractor.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/video/BackgroundSubtractorMOG2.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/video/BackgroundSubtractorKNN.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/ximgproc/ximgproc.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/ximgproc/MatXimgproc.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/ximgproc/SuperpixelSEEDS.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/ximgproc/SuperpixelSLIC.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/ximgproc/SuperpixelLSC.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/objdetect/objdetect.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/objdetect/CascadeClassifier.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/objdetect/HOGDescriptor.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/objdetect/DetectionROI.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/machinelearning/machinelearning.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/machinelearning/machinelearningConstants.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/machinelearning/ParamGrid.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/machinelearning/StatModel.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/machinelearning/SVM.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/machinelearning/TrainData.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/dnn/dnn.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/dnn/Net.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/face/face.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/face/FaceRecognizer.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/face/EigenFaceRecognizer.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/face/FisherFaceRecognizer.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/face/LBPHFaceRecognizer.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/face/Facemark.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/face/FacemarkAAM.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/face/FacemarkAAMData.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/face/FacemarkAAMParams.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/face/FacemarkLBF.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/face/FacemarkLBFParams.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/text/text.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/text/OCRHMMClassifier.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/text/OCRHMMDecoder.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/tracking/tracking.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/tracking/Tracker.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/tracking/MultiTracker.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/tracking/Trackers/TrackerBoosting.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/tracking/Trackers/TrackerBoostingParams.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/tracking/Trackers/TrackerKCF.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/tracking/Trackers/TrackerKCFParams.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/tracking/Trackers/TrackerMIL.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/tracking/Trackers/TrackerMILParams.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/tracking/Trackers/TrackerMedianFlow.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/tracking/Trackers/TrackerTLD.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/tracking/Trackers/TrackerGOTURN.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/tracking/Trackers/TrackerCSRT.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/tracking/Trackers/TrackerCSRTParams.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/tracking/Trackers/TrackerMOSSE.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/features2d/features2d.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/features2d/KeyPoint.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/features2d/KeyPointMatch.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/features2d/DescriptorMatch.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/features2d/BFMatcher.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/features2d/FeatureDetector.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/features2d/descriptorMatching.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/features2d/descriptorMatchingKnn.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/features2d/detectors/AGASTDetector.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/features2d/detectors/AKAZEDetector.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/features2d/detectors/BRISKDetector.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/features2d/detectors/FASTDetector.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/features2d/detectors/GFTTDetector.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/features2d/detectors/KAZEDetector.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/features2d/detectors/MSERDetector.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/features2d/detectors/ORBDetector.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/features2d/detectors/SimpleBlobDetector.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/features2d/detectors/SimpleBlobDetectorParams.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/xfeatures2d/xfeatures2d.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/xfeatures2d/SIFTDetector.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/xfeatures2d/SURFDetector.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/highgui/highgui.o
  CXX(target) Release/obj.target/opencv4nodejs/cc/highgui/highguiConstants.o
../cc/highgui/highgui.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE Highgui::getWindowProperty(Nan::NAN_METHOD_ARGS_TYPE)’:
../cc/highgui/highgui.cc:57:10: warning: unused variable ‘prop_value’ [-Wunused-variable]
   double prop_value;
          ^~~~~~~~~~
../cc/highgui/highgui.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE Highgui::setWindowProperty(Nan::NAN_METHOD_ARGS_TYPE)’:
../cc/highgui/highgui.cc:37:24: warning: ‘prop_value’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   cv::setWindowProperty(FF::StringConverter::unwrapUnchecked(info[0]), prop_id, prop_value);
   ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  SOLINK_MODULE(target) Release/obj.target/opencv4nodejs.node
  COPY Release/opencv4nodejs.node
make: Leaving directory '/home/ogata/work/fs/npm-test/check-opencv/node_modules/@u4/opencv4nodejs/build'
gyp info ok 
info install node-gyp complete successfully
```
</details>

The problem isn't there.
What I want to do is create `opencv4nodejs.node` from the **ALREADY BUILT** OpenCV modules they are shared and used in other projects.
I belong to a team that uses OpenCV for various purposes, 
so I would like to be able to reuse OpenCV built elsewhere and just build only `opencv4nodejs.node`.

The original `opencv4nodejs` could be built the way I first reported.
Do you intend to support the way this project?

> use OPENCV_BUILD_ROOT instead.

I understand that this proposed method only specifies the working directory for download and build,
and only if the same version is specified will it skip the OpenCV build.
However, I understand that it does not support to reuse of OpenCV binaries installed in `usr/local/lib` etc.

Please let me know if I'm misunderstanding.

**Comment by UrielCh** [comment]
I'm not focusing on using a prebuilt-version.
I will care about that once I will add option to share builds between different system, but before that I must reduce build size.

For now It you want to use pre-existing build, use the original `opencv4nodejs`, sorry.

**Comment by Shin-Ogata** [comment]
Unfortunately, [original one can't build with Nodejs v16](https://github.com/justadudewhohacks/opencv4nodejs/issues/837
), so it doesn't help me.
However I understand and respect your decision.
If you have time, I would be grateful if you could consider this feature again.
Thanks.

**Comment by UrielCh** [comment]
hi after a talk with @[piercus](https://github.com/piercus)

I decided to re-implement this feature.

The patched code needs to be tested.

**Comment by UrielCh** [comment]
tested, and working.
